export type ComparisonMappingConfidence = "high" | "medium" | "partial";

export type CanonicalComparisonCategoryDefinition = {
  key: string;
  label: string;
  shortLabel: string;
  color: string;
  isDefault: boolean;
  sortOrder: number;
};

export type LocationComparisonMappingDefinition = {
  canonicalKey: string;
  sourceLabels: string[];
  confidence: ComparisonMappingConfidence;
};

export const CANONICAL_COMPARISON_CATEGORIES: CanonicalComparisonCategoryDefinition[] = [
  { key: "total_offenses", label: "All recorded offenses", shortLabel: "All offenses", color: "#7dd3fc", isDefault: false, sortOrder: 1 },
  { key: "homicide", label: "Homicide", shortLabel: "Homicide", color: "#ef4444", isDefault: false, sortOrder: 2 },
  { key: "attempted_homicide", label: "Attempted homicide", shortLabel: "Attempted homicide", color: "#f97316", isDefault: false, sortOrder: 3 },
  { key: "sexual_offenses", label: "Sexual offenses", shortLabel: "Sexual offenses", color: "#ec4899", isDefault: false, sortOrder: 4 },
  { key: "sexual_violence", label: "Sexual violence / rape", shortLabel: "Sexual violence", color: "#d946ef", isDefault: false, sortOrder: 5 },
  { key: "other_sexual_offenses", label: "Other sexual offenses", shortLabel: "Other sexual", color: "#a78bfa", isDefault: false, sortOrder: 6 },
  { key: "robbery", label: "Robbery", shortLabel: "Robbery", color: "#f97316", isDefault: true, sortOrder: 7 },
  { key: "burglary", label: "Burglary", shortLabel: "Burglary", color: "#f59e0b", isDefault: false, sortOrder: 8 },
  { key: "residential_burglary", label: "Residential burglary", shortLabel: "Residential burglary", color: "#ef4444", isDefault: true, sortOrder: 9 },
  { key: "assault", label: "Assault", shortLabel: "Assault", color: "#38bdf8", isDefault: true, sortOrder: 10 },
  { key: "aggravated_assault", label: "Aggravated assault", shortLabel: "Agg. assault", color: "#0ea5e9", isDefault: false, sortOrder: 11 },
  { key: "theft", label: "Theft", shortLabel: "Theft", color: "#60a5fa", isDefault: false, sortOrder: 12 },
  { key: "personal_theft", label: "Personal theft", shortLabel: "Personal theft", color: "#67e8f9", isDefault: false, sortOrder: 13 },
  { key: "vehicle_theft", label: "Vehicle theft", shortLabel: "Vehicle theft", color: "#4f46e5", isDefault: true, sortOrder: 14 },
  { key: "theft_from_vehicles", label: "Theft from vehicles", shortLabel: "From vehicles", color: "#14b8a6", isDefault: false, sortOrder: 15 },
  { key: "bicycle_theft", label: "Bicycle theft", shortLabel: "Bike theft", color: "#2dd4bf", isDefault: false, sortOrder: 16 },
  { key: "drug_offenses", label: "Drug offenses", shortLabel: "Drug offenses", color: "#22c55e", isDefault: false, sortOrder: 17 },
  { key: "drug_trafficking", label: "Drug trafficking", shortLabel: "Drug trafficking", color: "#16a34a", isDefault: false, sortOrder: 18 },
  { key: "criminal_damage", label: "Criminal damage", shortLabel: "Criminal damage", color: "#f59e0b", isDefault: false, sortOrder: 19 },
  { key: "arson", label: "Arson", shortLabel: "Arson", color: "#fb7185", isDefault: false, sortOrder: 20 },
  { key: "fraud_and_deception", label: "Fraud and deception", shortLabel: "Fraud", color: "#94a3b8", isDefault: false, sortOrder: 21 },
  { key: "weapons_offenses", label: "Weapons offenses", shortLabel: "Weapons", color: "#fbbf24", isDefault: false, sortOrder: 22 },
  { key: "public_order", label: "Public order offenses", shortLabel: "Public order", color: "#8b5cf6", isDefault: false, sortOrder: 23 },
  { key: "stalking_harassment", label: "Threats, stalking & harassment", shortLabel: "Threats & stalking", color: "#c084fc", isDefault: false, sortOrder: 24 },
  { key: "cybercrime", label: "Cybercrime", shortLabel: "Cybercrime", color: "#818cf8", isDefault: false, sortOrder: 25 },
];

export const LOCATION_COMPARISON_MAPPINGS: Record<string, LocationComparisonMappingDefinition[]> = {
  austin: [
    { canonicalKey: "total_offenses", sourceLabels: ["All recorded offenses"], confidence: "high" },
    { canonicalKey: "homicide", sourceLabels: ["Homicide"], confidence: "high" },
    { canonicalKey: "sexual_offenses", sourceLabels: ["Sexual offenses"], confidence: "medium" },
    { canonicalKey: "robbery", sourceLabels: ["Robbery"], confidence: "high" },
    { canonicalKey: "burglary", sourceLabels: ["Burglary"], confidence: "high" },
    { canonicalKey: "residential_burglary", sourceLabels: ["Residential burglary"], confidence: "high" },
    { canonicalKey: "theft", sourceLabels: ["Theft"], confidence: "high" },
    { canonicalKey: "theft_from_vehicles", sourceLabels: ["Theft from vehicles"], confidence: "high" },
    { canonicalKey: "bicycle_theft", sourceLabels: ["Bicycle theft"], confidence: "high" },
    { canonicalKey: "vehicle_theft", sourceLabels: ["Motor vehicle theft"], confidence: "high" },
    { canonicalKey: "assault", sourceLabels: ["Assault"], confidence: "high" },
    { canonicalKey: "aggravated_assault", sourceLabels: ["Aggravated assault"], confidence: "high" },
    { canonicalKey: "drug_offenses", sourceLabels: ["Drug offenses"], confidence: "high" },
    { canonicalKey: "fraud_and_deception", sourceLabels: ["Fraud and forgery"], confidence: "high" },
    { canonicalKey: "criminal_damage", sourceLabels: ["Criminal damage"], confidence: "high" },
    { canonicalKey: "weapons_offenses", sourceLabels: ["Weapons offenses"], confidence: "medium" },
  ],
  barcelona: [
    { canonicalKey: "total_offenses", sourceLabels: ["All recorded offenses"], confidence: "high" },
    { canonicalKey: "assault", sourceLabels: ["Assaults and disorder"], confidence: "medium" },
    { canonicalKey: "sexual_offenses", sourceLabels: ["Sexual offenses"], confidence: "high" },
    { canonicalKey: "sexual_violence", sourceLabels: ["Penetrative sexual assault"], confidence: "high" },
    { canonicalKey: "other_sexual_offenses", sourceLabels: ["Other sexual offenses"], confidence: "high" },
    { canonicalKey: "robbery", sourceLabels: ["Robbery with violence or intimidation"], confidence: "medium" },
    { canonicalKey: "burglary", sourceLabels: ["Burglary and forced-entry theft"], confidence: "medium" },
    { canonicalKey: "residential_burglary", sourceLabels: ["Residential burglary"], confidence: "high" },
    { canonicalKey: "theft", sourceLabels: ["Theft"], confidence: "high" },
    { canonicalKey: "vehicle_theft", sourceLabels: ["Vehicle theft"], confidence: "high" },
    { canonicalKey: "drug_trafficking", sourceLabels: ["Drug trafficking"], confidence: "high" },
    { canonicalKey: "cybercrime", sourceLabels: ["Cybercrime"], confidence: "high" },
  ],
  birmingham: [
    { canonicalKey: "total_offenses", sourceLabels: ["All recorded offenses"], confidence: "high" },
    { canonicalKey: "homicide", sourceLabels: ["Homicide"], confidence: "high" },
    { canonicalKey: "sexual_offenses", sourceLabels: ["Sexual offences"], confidence: "high" },
    { canonicalKey: "robbery", sourceLabels: ["Robbery"], confidence: "high" },
    { canonicalKey: "assault", sourceLabels: ["Violence with injury", "Violence without injury"], confidence: "medium" },
    { canonicalKey: "theft", sourceLabels: ["Other theft", "Shoplifting", "Theft from person"], confidence: "medium" },
    { canonicalKey: "personal_theft", sourceLabels: ["Theft from person"], confidence: "high" },
    { canonicalKey: "vehicle_theft", sourceLabels: ["Vehicle offences"], confidence: "medium" },
    { canonicalKey: "bicycle_theft", sourceLabels: ["Bicycle theft"], confidence: "high" },
    { canonicalKey: "burglary", sourceLabels: ["Residential burglary", "Non-residential burglary"], confidence: "medium" },
    { canonicalKey: "residential_burglary", sourceLabels: ["Residential burglary"], confidence: "high" },
    { canonicalKey: "drug_offenses", sourceLabels: ["Drug offences"], confidence: "high" },
    { canonicalKey: "fraud_and_deception", sourceLabels: ["Fraud offences"], confidence: "high" },
    { canonicalKey: "public_order", sourceLabels: ["Public order offences"], confidence: "high" },
    { canonicalKey: "weapons_offenses", sourceLabels: ["Weapons possession"], confidence: "high" },
    { canonicalKey: "stalking_harassment", sourceLabels: ["Stalking and harassment"], confidence: "high" },
    { canonicalKey: "criminal_damage", sourceLabels: ["Criminal damage and arson"], confidence: "medium" },
  ],
  berlin: [
    { canonicalKey: "total_offenses", sourceLabels: ["All recorded offenses"], confidence: "high" },
    { canonicalKey: "robbery", sourceLabels: ["Robbery"], confidence: "high" },
    { canonicalKey: "assault", sourceLabels: ["All assaults"], confidence: "high" },
    { canonicalKey: "aggravated_assault", sourceLabels: ["Aggravated assault"], confidence: "high" },
    { canonicalKey: "stalking_harassment", sourceLabels: ["Coercion, threats & stalking"], confidence: "medium" },
    { canonicalKey: "theft", sourceLabels: ["All theft"], confidence: "high" },
    { canonicalKey: "vehicle_theft", sourceLabels: ["Motor vehicle theft"], confidence: "high" },
    { canonicalKey: "theft_from_vehicles", sourceLabels: ["Theft from vehicles"], confidence: "high" },
    { canonicalKey: "bicycle_theft", sourceLabels: ["Bicycle theft"], confidence: "high" },
    { canonicalKey: "residential_burglary", sourceLabels: ["Residential burglary"], confidence: "high" },
    { canonicalKey: "arson", sourceLabels: ["Arson"], confidence: "high" },
    { canonicalKey: "criminal_damage", sourceLabels: ["All criminal damage"], confidence: "high" },
    { canonicalKey: "drug_offenses", sourceLabels: ["Drug offenses"], confidence: "high" },
  ],
  chicago: [
    { canonicalKey: "total_offenses", sourceLabels: ["All recorded offenses"], confidence: "high" },
    { canonicalKey: "homicide", sourceLabels: ["Homicide"], confidence: "high" },
    { canonicalKey: "sexual_offenses", sourceLabels: ["Criminal sexual assault", "Other sexual offenses"], confidence: "medium" },
    { canonicalKey: "sexual_violence", sourceLabels: ["Criminal sexual assault"], confidence: "medium" },
    { canonicalKey: "other_sexual_offenses", sourceLabels: ["Other sexual offenses"], confidence: "high" },
    { canonicalKey: "robbery", sourceLabels: ["Robbery"], confidence: "high" },
    { canonicalKey: "burglary", sourceLabels: ["Burglary"], confidence: "high" },
    { canonicalKey: "assault", sourceLabels: ["Assault", "Battery"], confidence: "medium" },
    { canonicalKey: "theft", sourceLabels: ["Theft"], confidence: "high" },
    { canonicalKey: "vehicle_theft", sourceLabels: ["Motor vehicle theft"], confidence: "high" },
    { canonicalKey: "drug_offenses", sourceLabels: ["Drug offenses"], confidence: "high" },
    { canonicalKey: "weapons_offenses", sourceLabels: ["Weapons offenses"], confidence: "high" },
    { canonicalKey: "criminal_damage", sourceLabels: ["Criminal damage"], confidence: "high" },
    { canonicalKey: "fraud_and_deception", sourceLabels: ["Fraud and deception"], confidence: "high" },
    { canonicalKey: "arson", sourceLabels: ["Arson"], confidence: "high" },
  ],
  cleveland: [
    { canonicalKey: "total_offenses", sourceLabels: ["All recorded offenses"], confidence: "high" },
    { canonicalKey: "homicide", sourceLabels: ["Homicide"], confidence: "high" },
    { canonicalKey: "sexual_offenses", sourceLabels: ["Rape", "Other sexual offenses"], confidence: "medium" },
    { canonicalKey: "sexual_violence", sourceLabels: ["Rape"], confidence: "high" },
    { canonicalKey: "other_sexual_offenses", sourceLabels: ["Other sexual offenses"], confidence: "high" },
    { canonicalKey: "robbery", sourceLabels: ["Robbery"], confidence: "high" },
    { canonicalKey: "burglary", sourceLabels: ["Burglary"], confidence: "high" },
    { canonicalKey: "theft", sourceLabels: ["Theft"], confidence: "high" },
    { canonicalKey: "vehicle_theft", sourceLabels: ["Motor vehicle theft"], confidence: "high" },
    { canonicalKey: "assault", sourceLabels: ["Assault"], confidence: "high" },
    { canonicalKey: "aggravated_assault", sourceLabels: ["Aggravated assault"], confidence: "high" },
    { canonicalKey: "drug_offenses", sourceLabels: ["Drug offenses"], confidence: "high" },
    { canonicalKey: "fraud_and_deception", sourceLabels: ["Fraud and forgery"], confidence: "high" },
    { canonicalKey: "criminal_damage", sourceLabels: ["Criminal damage"], confidence: "high" },
    { canonicalKey: "weapons_offenses", sourceLabels: ["Weapons offenses"], confidence: "high" },
    { canonicalKey: "arson", sourceLabels: ["Arson"], confidence: "high" },
  ],
  dallas: [
    { canonicalKey: "total_offenses", sourceLabels: ["All recorded offenses"], confidence: "high" },
    { canonicalKey: "homicide", sourceLabels: ["Homicide"], confidence: "high" },
    { canonicalKey: "robbery", sourceLabels: ["Robbery"], confidence: "high" },
    { canonicalKey: "burglary", sourceLabels: ["Burglary"], confidence: "high" },
    { canonicalKey: "theft", sourceLabels: ["Theft"], confidence: "high" },
    { canonicalKey: "theft_from_vehicles", sourceLabels: ["Theft from vehicles"], confidence: "medium" },
    { canonicalKey: "vehicle_theft", sourceLabels: ["Motor vehicle theft"], confidence: "high" },
    { canonicalKey: "assault", sourceLabels: ["Assault"], confidence: "high" },
    { canonicalKey: "aggravated_assault", sourceLabels: ["Aggravated assault"], confidence: "high" },
    { canonicalKey: "drug_offenses", sourceLabels: ["Drug offenses"], confidence: "medium" },
    { canonicalKey: "fraud_and_deception", sourceLabels: ["Fraud and forgery"], confidence: "high" },
    { canonicalKey: "criminal_damage", sourceLabels: ["Criminal damage"], confidence: "high" },
    { canonicalKey: "weapons_offenses", sourceLabels: ["Weapons offenses"], confidence: "medium" },
    { canonicalKey: "arson", sourceLabels: ["Arson"], confidence: "high" },
  ],
  frankfurt: [
    { canonicalKey: "total_offenses", sourceLabels: ["All recorded offenses"], confidence: "high" },
    { canonicalKey: "sexual_offenses", sourceLabels: ["Sexual offenses"], confidence: "high" },
    { canonicalKey: "fraud_and_deception", sourceLabels: ["Financial and forgery offenses"], confidence: "medium" },
  ],
  france: [
    { canonicalKey: "assault", sourceLabels: ["Assault and battery"], confidence: "high" },
    { canonicalKey: "sexual_offenses", sourceLabels: ["Sexual violence"], confidence: "high" },
    { canonicalKey: "sexual_violence", sourceLabels: ["Sexual violence"], confidence: "medium" },
    { canonicalKey: "robbery", sourceLabels: ["Robbery and violent theft"], confidence: "medium" },
    { canonicalKey: "residential_burglary", sourceLabels: ["Residential burglary"], confidence: "high" },
    { canonicalKey: "vehicle_theft", sourceLabels: ["Vehicle theft"], confidence: "high" },
    { canonicalKey: "theft_from_vehicles", sourceLabels: ["Theft from vehicles"], confidence: "high" },
    { canonicalKey: "drug_offenses", sourceLabels: ["Drug offenses"], confidence: "high" },
    { canonicalKey: "fraud_and_deception", sourceLabels: ["Fraud and breach of trust"], confidence: "high" },
    { canonicalKey: "weapons_offenses", sourceLabels: ["Weapons offenses"], confidence: "high" },
    { canonicalKey: "stalking_harassment", sourceLabels: ["Threats and extortion"], confidence: "medium" },
  ],
  germany: [
    { canonicalKey: "total_offenses", sourceLabels: ["All recorded offenses"], confidence: "high" },
    { canonicalKey: "sexual_offenses", sourceLabels: ["Sexual offenses"], confidence: "high" },
    { canonicalKey: "robbery", sourceLabels: ["Robbery"], confidence: "high" },
    { canonicalKey: "assault", sourceLabels: ["Assault"], confidence: "high" },
    { canonicalKey: "stalking_harassment", sourceLabels: ["Threats, stalking & coercion"], confidence: "medium" },
    { canonicalKey: "theft", sourceLabels: ["Theft"], confidence: "high" },
    { canonicalKey: "vehicle_theft", sourceLabels: ["Vehicle theft"], confidence: "high" },
    { canonicalKey: "theft_from_vehicles", sourceLabels: ["Theft from vehicles"], confidence: "high" },
    { canonicalKey: "bicycle_theft", sourceLabels: ["Bicycle theft"], confidence: "high" },
    { canonicalKey: "personal_theft", sourceLabels: ["Pickpocketing"], confidence: "medium" },
    { canonicalKey: "residential_burglary", sourceLabels: ["Residential burglary"], confidence: "high" },
    { canonicalKey: "fraud_and_deception", sourceLabels: ["Fraud and deception"], confidence: "high" },
    { canonicalKey: "criminal_damage", sourceLabels: ["Criminal damage"], confidence: "high" },
    { canonicalKey: "drug_offenses", sourceLabels: ["Drug offenses"], confidence: "high" },
    { canonicalKey: "weapons_offenses", sourceLabels: ["Weapons offenses"], confidence: "high" },
  ],
  hamburg: [
    { canonicalKey: "total_offenses", sourceLabels: ["All recorded offenses"], confidence: "high" },
    { canonicalKey: "sexual_offenses", sourceLabels: ["Sexual offenses"], confidence: "high" },
    { canonicalKey: "sexual_violence", sourceLabels: ["Rape and severe sexual assault"], confidence: "medium" },
    { canonicalKey: "robbery", sourceLabels: ["Robbery"], confidence: "high" },
    { canonicalKey: "assault", sourceLabels: ["All assaults"], confidence: "high" },
    { canonicalKey: "aggravated_assault", sourceLabels: ["Aggravated assault"], confidence: "high" },
    { canonicalKey: "theft", sourceLabels: ["Theft"], confidence: "high" },
    { canonicalKey: "residential_burglary", sourceLabels: ["Residential burglary"], confidence: "high" },
    { canonicalKey: "vehicle_theft", sourceLabels: ["Vehicle theft"], confidence: "high" },
    { canonicalKey: "theft_from_vehicles", sourceLabels: ["Theft from vehicles"], confidence: "high" },
    { canonicalKey: "bicycle_theft", sourceLabels: ["Bicycle theft"], confidence: "high" },
    { canonicalKey: "fraud_and_deception", sourceLabels: ["Fraud"], confidence: "high" },
  ],
  houston: [
    { canonicalKey: "total_offenses", sourceLabels: ["All recorded offenses"], confidence: "high" },
    { canonicalKey: "homicide", sourceLabels: ["Homicide"], confidence: "high" },
    { canonicalKey: "sexual_offenses", sourceLabels: ["Sexual offenses"], confidence: "medium" },
    { canonicalKey: "robbery", sourceLabels: ["Robbery"], confidence: "high" },
    { canonicalKey: "burglary", sourceLabels: ["Burglary"], confidence: "high" },
    { canonicalKey: "theft", sourceLabels: ["Theft"], confidence: "high" },
    { canonicalKey: "vehicle_theft", sourceLabels: ["Motor vehicle theft"], confidence: "high" },
    { canonicalKey: "assault", sourceLabels: ["Assault"], confidence: "high" },
    { canonicalKey: "aggravated_assault", sourceLabels: ["Aggravated assault"], confidence: "high" },
    { canonicalKey: "drug_offenses", sourceLabels: ["Drug offenses"], confidence: "high" },
    { canonicalKey: "fraud_and_deception", sourceLabels: ["Fraud and forgery"], confidence: "high" },
    { canonicalKey: "criminal_damage", sourceLabels: ["Criminal damage"], confidence: "high" },
    { canonicalKey: "weapons_offenses", sourceLabels: ["Weapons offenses"], confidence: "high" },
    { canonicalKey: "arson", sourceLabels: ["Arson"], confidence: "high" },
  ],
  italy: [
    { canonicalKey: "sexual_offenses", sourceLabels: ["Sexual coercion and image abuse"], confidence: "medium" },
    { canonicalKey: "stalking_harassment", sourceLabels: ["Domestic abuse and stalking"], confidence: "medium" },
  ],
  spain: [
    { canonicalKey: "total_offenses", sourceLabels: ["All recorded offenses"], confidence: "high" },
    { canonicalKey: "assault", sourceLabels: ["Assaults and disorder"], confidence: "medium" },
    { canonicalKey: "sexual_offenses", sourceLabels: ["Sexual offenses"], confidence: "high" },
    { canonicalKey: "sexual_violence", sourceLabels: ["Penetrative sexual assault"], confidence: "high" },
    { canonicalKey: "other_sexual_offenses", sourceLabels: ["Other sexual offenses"], confidence: "high" },
    { canonicalKey: "robbery", sourceLabels: ["Robbery with violence or intimidation"], confidence: "medium" },
    { canonicalKey: "burglary", sourceLabels: ["Burglary and forced-entry theft"], confidence: "medium" },
    { canonicalKey: "residential_burglary", sourceLabels: ["Residential burglary"], confidence: "high" },
    { canonicalKey: "theft", sourceLabels: ["Theft"], confidence: "high" },
    { canonicalKey: "vehicle_theft", sourceLabels: ["Vehicle theft"], confidence: "high" },
    { canonicalKey: "drug_trafficking", sourceLabels: ["Drug trafficking"], confidence: "high" },
    { canonicalKey: "cybercrime", sourceLabels: ["Cybercrime"], confidence: "high" },
  ],
  london: [
    { canonicalKey: "total_offenses", sourceLabels: ["All recorded offenses"], confidence: "high" },
    { canonicalKey: "sexual_offenses", sourceLabels: ["Rape", "Other sexual offences"], confidence: "high" },
    { canonicalKey: "sexual_violence", sourceLabels: ["Rape"], confidence: "high" },
    { canonicalKey: "other_sexual_offenses", sourceLabels: ["Other sexual offences"], confidence: "high" },
    { canonicalKey: "vehicle_theft", sourceLabels: ["Motor vehicle theft"], confidence: "high" },
    { canonicalKey: "theft_from_vehicles", sourceLabels: ["Theft from vehicles"], confidence: "high" },
    { canonicalKey: "bicycle_theft", sourceLabels: ["Bicycle theft"], confidence: "high" },
    { canonicalKey: "residential_burglary", sourceLabels: ["Residential burglary"], confidence: "high" },
    { canonicalKey: "criminal_damage", sourceLabels: ["Criminal damage"], confidence: "high" },
    { canonicalKey: "arson", sourceLabels: ["Arson"], confidence: "high" },
    { canonicalKey: "drug_trafficking", sourceLabels: ["Drug trafficking"], confidence: "high" },
    { canonicalKey: "weapons_offenses", sourceLabels: ["Weapons possession"], confidence: "high" },
    { canonicalKey: "public_order", sourceLabels: ["Public order offences"], confidence: "high" },
  ],
  louisville: [
    { canonicalKey: "total_offenses", sourceLabels: ["All recorded offenses"], confidence: "high" },
    { canonicalKey: "homicide", sourceLabels: ["Homicide"], confidence: "high" },
    { canonicalKey: "sexual_offenses", sourceLabels: ["Sex crimes"], confidence: "medium" },
    { canonicalKey: "robbery", sourceLabels: ["Robbery"], confidence: "high" },
    { canonicalKey: "burglary", sourceLabels: ["Burglary"], confidence: "high" },
    { canonicalKey: "theft", sourceLabels: ["Theft"], confidence: "high" },
    { canonicalKey: "theft_from_vehicles", sourceLabels: ["Theft from vehicles"], confidence: "high" },
    { canonicalKey: "vehicle_theft", sourceLabels: ["Motor vehicle theft"], confidence: "high" },
    { canonicalKey: "assault", sourceLabels: ["Assault"], confidence: "high" },
    { canonicalKey: "drug_offenses", sourceLabels: ["Drug and alcohol violations"], confidence: "medium" },
    { canonicalKey: "fraud_and_deception", sourceLabels: ["Fraud"], confidence: "high" },
    { canonicalKey: "criminal_damage", sourceLabels: ["Criminal damage"], confidence: "high" },
    { canonicalKey: "weapons_offenses", sourceLabels: ["Weapons offenses"], confidence: "high" },
    { canonicalKey: "arson", sourceLabels: ["Arson"], confidence: "high" },
  ],
  "los-angeles": [
    { canonicalKey: "total_offenses", sourceLabels: ["All recorded offenses"], confidence: "high" },
    { canonicalKey: "homicide", sourceLabels: ["Homicide"], confidence: "high" },
    { canonicalKey: "sexual_offenses", sourceLabels: ["Sexual offenses"], confidence: "high" },
    { canonicalKey: "robbery", sourceLabels: ["Robbery"], confidence: "high" },
    { canonicalKey: "burglary", sourceLabels: ["Burglary"], confidence: "high" },
    { canonicalKey: "theft", sourceLabels: ["Theft"], confidence: "high" },
    { canonicalKey: "theft_from_vehicles", sourceLabels: ["Theft from vehicles"], confidence: "high" },
    { canonicalKey: "vehicle_theft", sourceLabels: ["Motor vehicle theft"], confidence: "high" },
    { canonicalKey: "assault", sourceLabels: ["Assaults"], confidence: "high" },
    { canonicalKey: "criminal_damage", sourceLabels: ["Criminal damage"], confidence: "high" },
    { canonicalKey: "fraud_and_deception", sourceLabels: ["Fraud and forgery"], confidence: "high" },
    { canonicalKey: "weapons_offenses", sourceLabels: ["Weapons incidents"], confidence: "medium" },
  ],
  luton: [
    { canonicalKey: "total_offenses", sourceLabels: ["All recorded offenses"], confidence: "high" },
    { canonicalKey: "homicide", sourceLabels: ["Homicide"], confidence: "high" },
    { canonicalKey: "sexual_offenses", sourceLabels: ["Sexual offences"], confidence: "high" },
    { canonicalKey: "robbery", sourceLabels: ["Robbery"], confidence: "high" },
    { canonicalKey: "personal_theft", sourceLabels: ["Theft from person"], confidence: "high" },
    { canonicalKey: "bicycle_theft", sourceLabels: ["Bicycle theft"], confidence: "high" },
    { canonicalKey: "residential_burglary", sourceLabels: ["Residential burglary"], confidence: "high" },
    { canonicalKey: "drug_offenses", sourceLabels: ["Drug offences"], confidence: "high" },
    { canonicalKey: "fraud_and_deception", sourceLabels: ["Fraud offences"], confidence: "high" },
    { canonicalKey: "public_order", sourceLabels: ["Public order offences"], confidence: "high" },
    { canonicalKey: "weapons_offenses", sourceLabels: ["Weapons possession"], confidence: "high" },
    { canonicalKey: "stalking_harassment", sourceLabels: ["Stalking and harassment"], confidence: "high" },
  ],
  manchester: [
    { canonicalKey: "total_offenses", sourceLabels: ["All recorded offenses"], confidence: "high" },
    { canonicalKey: "homicide", sourceLabels: ["Homicide"], confidence: "high" },
    { canonicalKey: "sexual_offenses", sourceLabels: ["Sexual offences"], confidence: "high" },
    { canonicalKey: "robbery", sourceLabels: ["Robbery"], confidence: "high" },
    { canonicalKey: "assault", sourceLabels: ["Violence with injury", "Violence without injury"], confidence: "medium" },
    { canonicalKey: "theft", sourceLabels: ["Other theft", "Shoplifting", "Theft from person"], confidence: "medium" },
    { canonicalKey: "personal_theft", sourceLabels: ["Theft from person"], confidence: "high" },
    { canonicalKey: "vehicle_theft", sourceLabels: ["Vehicle offences"], confidence: "medium" },
    { canonicalKey: "bicycle_theft", sourceLabels: ["Bicycle theft"], confidence: "high" },
    { canonicalKey: "burglary", sourceLabels: ["Residential burglary", "Non-residential burglary"], confidence: "medium" },
    { canonicalKey: "residential_burglary", sourceLabels: ["Residential burglary"], confidence: "high" },
    { canonicalKey: "drug_offenses", sourceLabels: ["Drug offences"], confidence: "high" },
    { canonicalKey: "fraud_and_deception", sourceLabels: ["Fraud offences"], confidence: "high" },
    { canonicalKey: "public_order", sourceLabels: ["Public order offences"], confidence: "high" },
    { canonicalKey: "weapons_offenses", sourceLabels: ["Weapons possession"], confidence: "high" },
    { canonicalKey: "stalking_harassment", sourceLabels: ["Stalking and harassment"], confidence: "high" },
    { canonicalKey: "criminal_damage", sourceLabels: ["Criminal damage and arson"], confidence: "medium" },
  ],
  melbourne: [
    { canonicalKey: "total_offenses", sourceLabels: ["All recorded offenses"], confidence: "high" },
    { canonicalKey: "homicide", sourceLabels: ["Homicide"], confidence: "high" },
    { canonicalKey: "sexual_offenses", sourceLabels: ["Sexual offenses"], confidence: "high" },
    { canonicalKey: "robbery", sourceLabels: ["Robbery"], confidence: "high" },
    { canonicalKey: "burglary", sourceLabels: ["Burglary"], confidence: "high" },
    { canonicalKey: "residential_burglary", sourceLabels: ["Residential burglary"], confidence: "high" },
    { canonicalKey: "theft", sourceLabels: ["Theft"], confidence: "high" },
    { canonicalKey: "bicycle_theft", sourceLabels: ["Bicycle theft"], confidence: "high" },
    { canonicalKey: "vehicle_theft", sourceLabels: ["Motor vehicle theft"], confidence: "high" },
    { canonicalKey: "theft_from_vehicles", sourceLabels: ["Theft from vehicles"], confidence: "high" },
    { canonicalKey: "assault", sourceLabels: ["Assault"], confidence: "high" },
    { canonicalKey: "aggravated_assault", sourceLabels: ["Aggravated assault"], confidence: "high" },
    { canonicalKey: "drug_offenses", sourceLabels: ["Drug offenses"], confidence: "high" },
    { canonicalKey: "drug_trafficking", sourceLabels: ["Drug trafficking"], confidence: "high" },
    { canonicalKey: "fraud_and_deception", sourceLabels: ["Fraud and deception"], confidence: "high" },
    { canonicalKey: "criminal_damage", sourceLabels: ["Criminal damage"], confidence: "high" },
    { canonicalKey: "arson", sourceLabels: ["Arson"], confidence: "high" },
    { canonicalKey: "weapons_offenses", sourceLabels: ["Weapons offenses"], confidence: "high" },
    { canonicalKey: "public_order", sourceLabels: ["Public order offenses"], confidence: "medium" },
    { canonicalKey: "stalking_harassment", sourceLabels: ["Stalking, harassment and threats"], confidence: "high" },
  ],
  milan: [
    { canonicalKey: "total_offenses", sourceLabels: ["All recorded offenses"], confidence: "high" },
    { canonicalKey: "theft", sourceLabels: ["Theft"], confidence: "high" },
    { canonicalKey: "robbery", sourceLabels: ["Robbery"], confidence: "high" },
    { canonicalKey: "sexual_violence", sourceLabels: ["Sexual violence"], confidence: "medium" },
    { canonicalKey: "assault", sourceLabels: ["Assaults"], confidence: "high" },
    { canonicalKey: "residential_burglary", sourceLabels: ["Residential burglary"], confidence: "high" },
    { canonicalKey: "vehicle_theft", sourceLabels: ["Vehicle theft"], confidence: "high" },
    { canonicalKey: "criminal_damage", sourceLabels: ["Criminal damage"], confidence: "high" },
    { canonicalKey: "drug_offenses", sourceLabels: ["Drug offenses"], confidence: "high" },
    { canonicalKey: "homicide", sourceLabels: ["Homicide"], confidence: "high" },
    { canonicalKey: "attempted_homicide", sourceLabels: ["Attempted homicide"], confidence: "high" },
    { canonicalKey: "arson", sourceLabels: ["Arson and fires"], confidence: "medium" },
  ],
  munich: [
    { canonicalKey: "total_offenses", sourceLabels: ["All recorded offenses"], confidence: "high" },
    { canonicalKey: "sexual_offenses", sourceLabels: ["Sexual offenses"], confidence: "high" },
    { canonicalKey: "sexual_violence", sourceLabels: ["Rape"], confidence: "high" },
    { canonicalKey: "robbery", sourceLabels: ["Robbery"], confidence: "high" },
    { canonicalKey: "theft", sourceLabels: ["Theft"], confidence: "high" },
    { canonicalKey: "vehicle_theft", sourceLabels: ["Vehicle theft"], confidence: "high" },
    { canonicalKey: "bicycle_theft", sourceLabels: ["Bicycle theft"], confidence: "high" },
    { canonicalKey: "drug_offenses", sourceLabels: ["Drug offenses"], confidence: "high" },
    { canonicalKey: "fraud_and_deception", sourceLabels: ["Fraud and embezzlement"], confidence: "medium" },
  ],
  minneapolis: [
    { canonicalKey: "total_offenses", sourceLabels: ["All recorded offenses"], confidence: "high" },
    { canonicalKey: "homicide", sourceLabels: ["Homicide"], confidence: "high" },
    { canonicalKey: "sexual_offenses", sourceLabels: ["Rape"], confidence: "medium" },
    { canonicalKey: "sexual_violence", sourceLabels: ["Rape"], confidence: "high" },
    { canonicalKey: "robbery", sourceLabels: ["Robbery"], confidence: "high" },
    { canonicalKey: "burglary", sourceLabels: ["Burglary"], confidence: "high" },
    { canonicalKey: "theft", sourceLabels: ["Larceny theft"], confidence: "high" },
    { canonicalKey: "vehicle_theft", sourceLabels: ["Motor vehicle theft"], confidence: "high" },
    { canonicalKey: "aggravated_assault", sourceLabels: ["Aggravated assault"], confidence: "high" },
    { canonicalKey: "arson", sourceLabels: ["Arson"], confidence: "high" },
  ],
  "new-york-city": [
    { canonicalKey: "total_offenses", sourceLabels: ["All recorded offenses"], confidence: "high" },
    { canonicalKey: "homicide", sourceLabels: ["Homicide"], confidence: "high" },
    { canonicalKey: "sexual_offenses", sourceLabels: ["Rape", "Other sexual offenses"], confidence: "high" },
    { canonicalKey: "sexual_violence", sourceLabels: ["Rape"], confidence: "high" },
    { canonicalKey: "other_sexual_offenses", sourceLabels: ["Other sexual offenses"], confidence: "high" },
    { canonicalKey: "robbery", sourceLabels: ["Robbery"], confidence: "high" },
    { canonicalKey: "burglary", sourceLabels: ["Burglary"], confidence: "high" },
    { canonicalKey: "theft", sourceLabels: ["Petit larceny", "Grand larceny"], confidence: "medium" },
    { canonicalKey: "vehicle_theft", sourceLabels: ["Motor vehicle theft"], confidence: "high" },
    { canonicalKey: "drug_offenses", sourceLabels: ["Drug offenses"], confidence: "high" },
    { canonicalKey: "weapons_offenses", sourceLabels: ["Weapons offenses"], confidence: "high" },
    { canonicalKey: "criminal_damage", sourceLabels: ["Criminal mischief"], confidence: "high" },
    { canonicalKey: "fraud_and_deception", sourceLabels: ["Fraud and forgery"], confidence: "high" },
  ],
  paris: [
    { canonicalKey: "total_offenses", sourceLabels: ["All recorded offenses"], confidence: "high" },
    { canonicalKey: "sexual_violence", sourceLabels: ["Sexual violence"], confidence: "medium" },
    { canonicalKey: "robbery", sourceLabels: ["Armed theft", "Violent theft without weapon"], confidence: "medium" },
    { canonicalKey: "personal_theft", sourceLabels: ["Non-violent personal theft"], confidence: "high" },
    { canonicalKey: "residential_burglary", sourceLabels: ["Residential burglary"], confidence: "high" },
    { canonicalKey: "vehicle_theft", sourceLabels: ["Vehicle theft"], confidence: "high" },
    { canonicalKey: "theft_from_vehicles", sourceLabels: ["Theft from vehicles"], confidence: "high" },
    { canonicalKey: "criminal_damage", sourceLabels: ["Criminal damage"], confidence: "high" },
    { canonicalKey: "drug_trafficking", sourceLabels: ["Drug trafficking"], confidence: "high" },
    { canonicalKey: "fraud_and_deception", sourceLabels: ["Payment fraud and scams"], confidence: "medium" },
  ],
  phoenix: [
    { canonicalKey: "total_offenses", sourceLabels: ["All recorded offenses"], confidence: "high" },
    { canonicalKey: "homicide", sourceLabels: ["Homicide"], confidence: "high" },
    { canonicalKey: "sexual_violence", sourceLabels: ["Rape"], confidence: "high" },
    { canonicalKey: "robbery", sourceLabels: ["Robbery"], confidence: "high" },
    { canonicalKey: "burglary", sourceLabels: ["Burglary"], confidence: "high" },
    { canonicalKey: "theft", sourceLabels: ["Larceny theft"], confidence: "high" },
    { canonicalKey: "vehicle_theft", sourceLabels: ["Motor vehicle theft"], confidence: "high" },
    { canonicalKey: "assault", sourceLabels: ["Simple assault"], confidence: "high" },
    { canonicalKey: "aggravated_assault", sourceLabels: ["Aggravated assault"], confidence: "high" },
    { canonicalKey: "drug_offenses", sourceLabels: ["Drug offenses"], confidence: "high" },
    { canonicalKey: "arson", sourceLabels: ["Arson"], confidence: "high" },
  ],
  rome: [
    { canonicalKey: "total_offenses", sourceLabels: ["All recorded offenses"], confidence: "high" },
    { canonicalKey: "theft", sourceLabels: ["Theft"], confidence: "high" },
    { canonicalKey: "robbery", sourceLabels: ["Robbery"], confidence: "high" },
    { canonicalKey: "sexual_offenses", sourceLabels: ["Sexual violence", "Other sexual offenses"], confidence: "medium" },
    { canonicalKey: "sexual_violence", sourceLabels: ["Sexual violence"], confidence: "medium" },
    { canonicalKey: "other_sexual_offenses", sourceLabels: ["Other sexual offenses"], confidence: "high" },
    { canonicalKey: "drug_offenses", sourceLabels: ["Drug offenses"], confidence: "high" },
    { canonicalKey: "fraud_and_deception", sourceLabels: ["Cyber fraud"], confidence: "medium" },
    { canonicalKey: "criminal_damage", sourceLabels: ["Criminal damage"], confidence: "high" },
    { canonicalKey: "assault", sourceLabels: ["Assaults"], confidence: "high" },
    { canonicalKey: "homicide", sourceLabels: ["Homicide"], confidence: "high" },
    { canonicalKey: "attempted_homicide", sourceLabels: ["Attempted homicide"], confidence: "high" },
  ],
  "sao-paulo": [
    { canonicalKey: "total_offenses", sourceLabels: ["All recorded offenses"], confidence: "high" },
    { canonicalKey: "homicide", sourceLabels: ["Homicide"], confidence: "high" },
    { canonicalKey: "attempted_homicide", sourceLabels: ["Attempted homicide"], confidence: "high" },
    { canonicalKey: "sexual_offenses", sourceLabels: ["Sexual offenses"], confidence: "high" },
    { canonicalKey: "sexual_violence", sourceLabels: ["Rape"], confidence: "high" },
    { canonicalKey: "assault", sourceLabels: ["Assault"], confidence: "high" },
    { canonicalKey: "robbery", sourceLabels: ["Robbery"], confidence: "high" },
    { canonicalKey: "theft", sourceLabels: ["Theft"], confidence: "high" },
    { canonicalKey: "vehicle_theft", sourceLabels: ["Vehicle theft"], confidence: "high" },
    { canonicalKey: "drug_trafficking", sourceLabels: ["Drug trafficking"], confidence: "high" },
  ],
  "san-francisco": [
    { canonicalKey: "total_offenses", sourceLabels: ["All recorded offenses"], confidence: "high" },
    { canonicalKey: "homicide", sourceLabels: ["Homicide"], confidence: "high" },
    { canonicalKey: "sexual_offenses", sourceLabels: ["Rape", "Other sexual offenses"], confidence: "high" },
    { canonicalKey: "sexual_violence", sourceLabels: ["Rape"], confidence: "high" },
    { canonicalKey: "other_sexual_offenses", sourceLabels: ["Other sexual offenses"], confidence: "high" },
    { canonicalKey: "robbery", sourceLabels: ["Robbery"], confidence: "high" },
    { canonicalKey: "burglary", sourceLabels: ["Burglary"], confidence: "high" },
    { canonicalKey: "assault", sourceLabels: ["Assault"], confidence: "high" },
    { canonicalKey: "theft", sourceLabels: ["Larceny theft"], confidence: "high" },
    { canonicalKey: "vehicle_theft", sourceLabels: ["Motor vehicle theft"], confidence: "high" },
    { canonicalKey: "drug_offenses", sourceLabels: ["Drug offenses"], confidence: "high" },
    { canonicalKey: "weapons_offenses", sourceLabels: ["Weapons offenses"], confidence: "high" },
    { canonicalKey: "fraud_and_deception", sourceLabels: ["Fraud and forgery"], confidence: "high" },
    { canonicalKey: "criminal_damage", sourceLabels: ["Criminal damage"], confidence: "high" },
  ],
  seattle: [
    { canonicalKey: "total_offenses", sourceLabels: ["All recorded offenses"], confidence: "high" },
    { canonicalKey: "homicide", sourceLabels: ["Homicide"], confidence: "high" },
    { canonicalKey: "sexual_offenses", sourceLabels: ["Rape", "Other sexual offenses"], confidence: "high" },
    { canonicalKey: "sexual_violence", sourceLabels: ["Rape"], confidence: "high" },
    { canonicalKey: "other_sexual_offenses", sourceLabels: ["Other sexual offenses"], confidence: "high" },
    { canonicalKey: "robbery", sourceLabels: ["Robbery"], confidence: "high" },
    { canonicalKey: "burglary", sourceLabels: ["Burglary"], confidence: "high" },
    { canonicalKey: "theft", sourceLabels: ["Theft"], confidence: "high" },
    { canonicalKey: "theft_from_vehicles", sourceLabels: ["Theft from vehicles"], confidence: "high" },
    { canonicalKey: "vehicle_theft", sourceLabels: ["Motor vehicle theft"], confidence: "high" },
    { canonicalKey: "assault", sourceLabels: ["Assault"], confidence: "high" },
    { canonicalKey: "aggravated_assault", sourceLabels: ["Aggravated assault"], confidence: "high" },
    { canonicalKey: "drug_offenses", sourceLabels: ["Drug offenses"], confidence: "high" },
    { canonicalKey: "fraud_and_deception", sourceLabels: ["Fraud and forgery"], confidence: "high" },
    { canonicalKey: "criminal_damage", sourceLabels: ["Criminal damage"], confidence: "high" },
    { canonicalKey: "weapons_offenses", sourceLabels: ["Weapons offenses"], confidence: "high" },
    { canonicalKey: "arson", sourceLabels: ["Arson"], confidence: "high" },
  ],
  sydney: [
    { canonicalKey: "total_offenses", sourceLabels: ["All recorded offenses"], confidence: "high" },
    { canonicalKey: "homicide", sourceLabels: ["Homicide"], confidence: "high" },
    { canonicalKey: "attempted_homicide", sourceLabels: ["Attempted homicide"], confidence: "high" },
    { canonicalKey: "sexual_offenses", sourceLabels: ["Sexual offenses"], confidence: "high" },
    { canonicalKey: "sexual_violence", sourceLabels: ["Sexual assault"], confidence: "high" },
    { canonicalKey: "other_sexual_offenses", sourceLabels: ["Other sexual offenses"], confidence: "high" },
    { canonicalKey: "robbery", sourceLabels: ["Robbery"], confidence: "high" },
    { canonicalKey: "burglary", sourceLabels: ["Burglary"], confidence: "high" },
    { canonicalKey: "residential_burglary", sourceLabels: ["Residential burglary"], confidence: "high" },
    { canonicalKey: "theft", sourceLabels: ["Theft"], confidence: "high" },
    { canonicalKey: "personal_theft", sourceLabels: ["Personal theft"], confidence: "high" },
    { canonicalKey: "vehicle_theft", sourceLabels: ["Motor vehicle theft"], confidence: "high" },
    { canonicalKey: "theft_from_vehicles", sourceLabels: ["Theft from vehicles"], confidence: "high" },
    { canonicalKey: "assault", sourceLabels: ["Assault"], confidence: "high" },
    { canonicalKey: "drug_offenses", sourceLabels: ["Drug offenses"], confidence: "high" },
    { canonicalKey: "drug_trafficking", sourceLabels: ["Drug trafficking"], confidence: "high" },
    { canonicalKey: "fraud_and_deception", sourceLabels: ["Fraud and deception"], confidence: "high" },
    { canonicalKey: "criminal_damage", sourceLabels: ["Criminal damage"], confidence: "high" },
    { canonicalKey: "arson", sourceLabels: ["Arson"], confidence: "high" },
    { canonicalKey: "weapons_offenses", sourceLabels: ["Weapons offenses"], confidence: "high" },
    { canonicalKey: "public_order", sourceLabels: ["Public order offenses"], confidence: "medium" },
    { canonicalKey: "stalking_harassment", sourceLabels: ["Stalking, harassment and threats"], confidence: "high" },
  ],
  tokyo: [
    { canonicalKey: "total_offenses", sourceLabels: ["All recorded offenses"], confidence: "high" },
    { canonicalKey: "homicide", sourceLabels: ["Homicide"], confidence: "high" },
    { canonicalKey: "sexual_violence", sourceLabels: ["Penetrative sexual assault"], confidence: "medium" },
    { canonicalKey: "robbery", sourceLabels: ["Robbery"], confidence: "medium" },
    { canonicalKey: "assault", sourceLabels: ["Violence", "Bodily injury"], confidence: "medium" },
    { canonicalKey: "burglary", sourceLabels: ["Breaking-and-entering theft"], confidence: "medium" },
    { canonicalKey: "theft", sourceLabels: ["Theft without breaking and entering"], confidence: "high" },
    { canonicalKey: "fraud_and_deception", sourceLabels: ["Fraud"], confidence: "high" },
    { canonicalKey: "arson", sourceLabels: ["Arson"], confidence: "high" },
    { canonicalKey: "criminal_damage", sourceLabels: ["Criminal damage"], confidence: "high" },
  ],
  valencia: [
    { canonicalKey: "total_offenses", sourceLabels: ["All recorded offenses"], confidence: "high" },
    { canonicalKey: "assault", sourceLabels: ["Assaults and disorder"], confidence: "medium" },
    { canonicalKey: "sexual_offenses", sourceLabels: ["Sexual offenses"], confidence: "high" },
    { canonicalKey: "sexual_violence", sourceLabels: ["Penetrative sexual assault"], confidence: "high" },
    { canonicalKey: "other_sexual_offenses", sourceLabels: ["Other sexual offenses"], confidence: "high" },
    { canonicalKey: "robbery", sourceLabels: ["Robbery with violence or intimidation"], confidence: "medium" },
    { canonicalKey: "burglary", sourceLabels: ["Burglary and forced-entry theft"], confidence: "medium" },
    { canonicalKey: "residential_burglary", sourceLabels: ["Residential burglary"], confidence: "high" },
    { canonicalKey: "theft", sourceLabels: ["Theft"], confidence: "high" },
    { canonicalKey: "vehicle_theft", sourceLabels: ["Vehicle theft"], confidence: "high" },
    { canonicalKey: "drug_trafficking", sourceLabels: ["Drug trafficking"], confidence: "high" },
    { canonicalKey: "cybercrime", sourceLabels: ["Cybercrime"], confidence: "high" },
  ],
};

export function isComparableMappingConfidence(confidence: ComparisonMappingConfidence) {
  return confidence === "high" || confidence === "medium";
}
