export type LocationCategoryDefinition = {
  sourceLabels: string[];
  label: string;
  shortLabel: string;
  color: string;
  isDefault: boolean;
  sortOrder: number;
};

export type LocationDefinition = {
  slug: string;
  label: string;
  country: string;
  areaLabelSingular: string;
  areaLabelPlural: string;
  chartTitle: string;
  note: string;
  sources: Array<{
    label: string;
    url?: string;
  }>;
  categories: LocationCategoryDefinition[];
};

export const BERLIN_LOCATION: LocationDefinition = {
  slug: "berlin",
  label: "Berlin",
  country: "Germany",
  areaLabelSingular: "District",
  areaLabelPlural: "Districts",
  chartTitle: "Berlin Crime by District",
  note:
    "Berlin uses official Polizei Berlin atlas categories. Some categories are umbrella groups while others are nested subtypes, so the stacks are best read as comparison views rather than deduplicated totals.",
  sources: [
    {
      label: "Polizei Berlin Kriminalitätsatlas",
      url: "https://www.berlin.de/polizei/service/kriminalitaetsatlas/",
    },
    {
      label: "Polizei Berlin PKS archive and historical atlas reports",
      url: "https://www.berlin.de/polizei/verschiedenes/polizeiliche-kriminalstatistik/",
    },
    {
      label: "Current district workbook from the official atlas",
      url: "https://www.kriminalitaetsatlas.berlin.de/K-Atlas/bezirke/Fallzahlen%26HZ%202015-2024.xlsx",
    },
  ],
  categories: [
    {
      sourceLabels: ["Straftaten -insgesamt-"],
      label: "All recorded offenses",
      shortLabel: "All offenses",
      color: "#7dd3fc",
      isDefault: false,
      sortOrder: 1,
    },
    {
      sourceLabels: ["Raub"],
      label: "Robbery",
      shortLabel: "Robbery",
      color: "#f97316",
      isDefault: true,
      sortOrder: 2,
    },
    {
      sourceLabels: ["Straßenraub, Handtaschenraub"],
      label: "Street / bag robbery",
      shortLabel: "Street robbery",
      color: "#facc15",
      isDefault: true,
      sortOrder: 3,
    },
    {
      sourceLabels: ["Körperverletzungen -insgesamt-"],
      label: "All assaults",
      shortLabel: "All assaults",
      color: "#38bdf8",
      isDefault: false,
      sortOrder: 4,
    },
    {
      sourceLabels: ["Gefährl. und schwere Körperverletzung"],
      label: "Aggravated assault",
      shortLabel: "Agg. assault",
      color: "#0ea5e9",
      isDefault: true,
      sortOrder: 5,
    },
    {
      sourceLabels: ["Freiheitsberaubung, Nötigung, Bedrohung, Nachstellung"],
      label: "Coercion, threats & stalking",
      shortLabel: "Threats & stalking",
      color: "#a78bfa",
      isDefault: true,
      sortOrder: 6,
    },
    {
      sourceLabels: ["Diebstahl -insgesamt-"],
      label: "All theft",
      shortLabel: "All theft",
      color: "#60a5fa",
      isDefault: false,
      sortOrder: 7,
    },
    {
      sourceLabels: ["Diebstahl von Kraftwagen"],
      label: "Motor vehicle theft",
      shortLabel: "Vehicle theft",
      color: "#4f46e5",
      isDefault: true,
      sortOrder: 8,
    },
    {
      sourceLabels: ["Diebstahl an/aus Kfz"],
      label: "Theft from vehicles",
      shortLabel: "From vehicles",
      color: "#14b8a6",
      isDefault: false,
      sortOrder: 9,
    },
    {
      sourceLabels: ["Fahrraddiebstahl"],
      label: "Bicycle theft",
      shortLabel: "Bike theft",
      color: "#2dd4bf",
      isDefault: false,
      sortOrder: 10,
    },
    {
      sourceLabels: ["Wohnraumeinbruch"],
      label: "Residential burglary",
      shortLabel: "Burglary",
      color: "#ef4444",
      isDefault: true,
      sortOrder: 11,
    },
    {
      sourceLabels: ["Branddelikte -insgesamt-"],
      label: "All arson-related offenses",
      shortLabel: "All arson",
      color: "#fb7185",
      isDefault: false,
      sortOrder: 12,
    },
    {
      sourceLabels: ["Brandstiftung"],
      label: "Arson",
      shortLabel: "Arson",
      color: "#ec4899",
      isDefault: true,
      sortOrder: 13,
    },
    {
      sourceLabels: ["Sachbeschädigung -insgesamt-"],
      label: "All criminal damage",
      shortLabel: "All damage",
      color: "#f59e0b",
      isDefault: false,
      sortOrder: 14,
    },
    {
      sourceLabels: ["Sachbeschädigung durch Graffiti"],
      label: "Graffiti damage",
      shortLabel: "Graffiti",
      color: "#fbbf24",
      isDefault: false,
      sortOrder: 15,
    },
    {
      sourceLabels: ["Rauschgiftdelikte"],
      label: "Drug offenses",
      shortLabel: "Drug offenses",
      color: "#22c55e",
      isDefault: false,
      sortOrder: 16,
    },
    {
      sourceLabels: ["Kieztaten"],
      label: "Neighborhood offenses",
      shortLabel: "Neighborhood",
      color: "#34d399",
      isDefault: false,
      sortOrder: 17,
    },
  ],
};

export const LONDON_LOCATION: LocationDefinition = {
  slug: "london",
  label: "London",
  country: "United Kingdom",
  areaLabelSingular: "Borough",
  areaLabelPlural: "Boroughs",
  chartTitle: "London Crime by Borough",
  note:
    "London uses official Metropolitan Police recorded-crime categories aggregated to calendar years. A few categories were renamed over time, and those official aliases are merged where the dataset clearly indicates the same series.",
  sources: [
    {
      label: "MPS Recorded Crime: Geographic Breakdown dataset",
      url: "https://data.london.gov.uk/dataset/recorded_crime_summary/resource/760704bd-7d54-485c-9509-e06ff547766d",
    },
    {
      label: "ONS borough population estimates via London Datastore",
      url: "https://data.london.gov.uk/dataset/office-for-national-statistics-ons-population-estimates-borough--vd615/",
    },
    {
      label: "ONS England and Wales local-authority population workbook",
      url: "https://www.ons.gov.uk/file?uri=%2Fpeoplepopulationandcommunity%2Fpopulationandmigration%2Fpopulationestimates%2Fdatasets%2Festimatesofthepopulationforenglandandwales%2Fmid2011tomid2024detailedtimeseries%2Fmyebtablesenglandwales20112024.xlsx",
    },
  ],
  categories: [
    {
      sourceLabels: ["ROBBERY OF PERSONAL PROPERTY"],
      label: "Personal robbery",
      shortLabel: "Robbery",
      color: "#f97316",
      isDefault: true,
      sortOrder: 1,
    },
    {
      sourceLabels: ["ROBBERY OF BUSINESS PROPERTY"],
      label: "Business robbery",
      shortLabel: "Business robbery",
      color: "#fb923c",
      isDefault: false,
      sortOrder: 2,
    },
    {
      sourceLabels: ["VIOLENCE WITH INJURY"],
      label: "Violence with injury",
      shortLabel: "Violence w/ injury",
      color: "#facc15",
      isDefault: true,
      sortOrder: 3,
    },
    {
      sourceLabels: ["VIOLENCE WITHOUT INJURY"],
      label: "Violence without injury",
      shortLabel: "Violence no injury",
      color: "#fde047",
      isDefault: false,
      sortOrder: 4,
    },
    {
      sourceLabels: ["RAPE"],
      label: "Rape",
      shortLabel: "Rape",
      color: "#38bdf8",
      isDefault: true,
      sortOrder: 5,
    },
    {
      sourceLabels: ["OTHER SEXUAL OFFENCES"],
      label: "Other sexual offences",
      shortLabel: "Other sexual",
      color: "#a78bfa",
      isDefault: true,
      sortOrder: 6,
    },
    {
      sourceLabels: ["THEFT FROM THE PERSON"],
      label: "Theft from person",
      shortLabel: "From person",
      color: "#67e8f9",
      isDefault: false,
      sortOrder: 7,
    },
    {
      sourceLabels: ["THEFT OR UNAUTH TAKING OF A MOTOR VEH", "AGGRAVATED VEHICLE TAKING"],
      label: "Motor vehicle theft",
      shortLabel: "Vehicle theft",
      color: "#4f46e5",
      isDefault: true,
      sortOrder: 8,
    },
    {
      sourceLabels: ["THEFT FROM A VEHICLE", "INTERFERING WITH A MOTOR VEHICLE"],
      label: "Theft from vehicles",
      shortLabel: "From vehicles",
      color: "#6366f1",
      isDefault: false,
      sortOrder: 9,
    },
    {
      sourceLabels: ["BICYCLE THEFT"],
      label: "Bicycle theft",
      shortLabel: "Bike theft",
      color: "#22d3ee",
      isDefault: false,
      sortOrder: 10,
    },
    {
      sourceLabels: ["BURGLARY IN A DWELLING", "BURGLARY - RESIDENTIAL"],
      label: "Residential burglary",
      shortLabel: "Burglary",
      color: "#ef4444",
      isDefault: true,
      sortOrder: 11,
    },
    {
      sourceLabels: ["BURGLARY BUSINESS AND COMMUNITY", "BURGLARY NON-DWELLING"],
      label: "Non-residential burglary",
      shortLabel: "Non-res burglary",
      color: "#f87171",
      isDefault: false,
      sortOrder: 12,
    },
    {
      sourceLabels: ["CRIMINAL DAMAGE"],
      label: "Criminal damage",
      shortLabel: "Criminal damage",
      color: "#ec4899",
      isDefault: true,
      sortOrder: 13,
    },
    {
      sourceLabels: ["ARSON"],
      label: "Arson",
      shortLabel: "Arson",
      color: "#fb7185",
      isDefault: false,
      sortOrder: 14,
    },
    {
      sourceLabels: ["POSSESSION OF DRUGS"],
      label: "Drug possession",
      shortLabel: "Drug possession",
      color: "#22c55e",
      isDefault: false,
      sortOrder: 15,
    },
    {
      sourceLabels: ["TRAFFICKING OF DRUGS"],
      label: "Drug trafficking",
      shortLabel: "Drug trafficking",
      color: "#16a34a",
      isDefault: false,
      sortOrder: 16,
    },
    {
      sourceLabels: ["POSSESSION OF WEAPONS"],
      label: "Weapons possession",
      shortLabel: "Weapons",
      color: "#eab308",
      isDefault: false,
      sortOrder: 17,
    },
    {
      sourceLabels: [
        "OTHER OFFENCES PUBLIC ORDER",
        "PUBLIC FEAR ALARM OR DISTRESS",
        "RACE OR RELIGIOUS AGG PUBLIC FEAR",
        "VIOLENT DISORDER",
      ],
      label: "Public order offences",
      shortLabel: "Public order",
      color: "#c084fc",
      isDefault: false,
      sortOrder: 18,
    },
    {
      sourceLabels: ["OTHER THEFT"],
      label: "Other theft",
      shortLabel: "Other theft",
      color: "#60a5fa",
      isDefault: false,
      sortOrder: 19,
    },
    {
      sourceLabels: ["SHOPLIFTING"],
      label: "Shoplifting",
      shortLabel: "Shoplifting",
      color: "#93c5fd",
      isDefault: false,
      sortOrder: 20,
    },
  ],
};

export const FRANKFURT_LOCATION: LocationDefinition = {
  slug: "frankfurt",
  label: "Frankfurt",
  country: "Germany",
  areaLabelSingular: "Area",
  areaLabelPlural: "Areas",
  chartTitle: "Frankfurt Crime Overview",
  note:
    "Frankfurt currently uses official citywide open-data crime series from the City of Frankfurt and the Hessisches Landeskriminalamt. These categories are annual city totals rather than district-level atlas slices.",
  sources: [
    {
      label: "City of Frankfurt open data: crimes by offense type",
      url: "https://offenedaten.frankfurt.de/dcat/dataset/de-he-frankfurtam-straftaten_nach_art_der_straftat.html",
    },
    {
      label: "City of Frankfurt open data: citywide demographic indicators",
      url: "https://offenedaten.frankfurt.de/dcat/dataset/de-he-frankfurtam-demographische_kennzahlen_gesamtstaedtisch.html",
    },
  ],
  categories: [
    {
      sourceLabels: ["insgesamt"],
      label: "All recorded offenses",
      shortLabel: "All offenses",
      color: "#7dd3fc",
      isDefault: false,
      sortOrder: 1,
    },
    {
      sourceLabels: ["Straftaten gegen das Leben"],
      label: "Offenses against life",
      shortLabel: "Against life",
      color: "#fb7185",
      isDefault: false,
      sortOrder: 2,
    },
    {
      sourceLabels: ["Straftaten gegen die sexuelle Selbstbestimmung"],
      label: "Sexual offenses",
      shortLabel: "Sexual offenses",
      color: "#ec4899",
      isDefault: true,
      sortOrder: 3,
    },
    {
      sourceLabels: ["Rohheitsdelikte und Straftaten gegen die persönliche Freiheit"],
      label: "Violence and personal freedom",
      shortLabel: "Violence & freedom",
      color: "#f97316",
      isDefault: true,
      sortOrder: 4,
    },
    {
      sourceLabels: ["Eigentumsdelikte"],
      label: "Property offenses",
      shortLabel: "Property",
      color: "#38bdf8",
      isDefault: false,
      sortOrder: 5,
    },
    {
      sourceLabels: ["ohne erschwerende Umstände"],
      label: "Simple theft and related offenses",
      shortLabel: "Simple theft",
      color: "#0ea5e9",
      isDefault: true,
      sortOrder: 6,
    },
    {
      sourceLabels: ["unter erschwerenden Umständen"],
      label: "Aggravated theft and related offenses",
      shortLabel: "Aggr. theft",
      color: "#4f46e5",
      isDefault: true,
      sortOrder: 7,
    },
    {
      sourceLabels: ["Vermögens- und Fälschungsdelikte"],
      label: "Financial and forgery offenses",
      shortLabel: "Financial & forgery",
      color: "#a78bfa",
      isDefault: true,
      sortOrder: 8,
    },
    {
      sourceLabels: ["sonstige Straftatbestände nach dem Strafgesetzbuch"],
      label: "Other criminal code offenses",
      shortLabel: "Other criminal code",
      color: "#f59e0b",
      isDefault: false,
      sortOrder: 9,
    },
    {
      sourceLabels: ["strafrechtliche Nebengesetze"],
      label: "Ancillary criminal-law offenses",
      shortLabel: "Ancillary laws",
      color: "#22c55e",
      isDefault: false,
      sortOrder: 10,
    },
  ],
};

export const LUTON_LOCATION: LocationDefinition = {
  slug: "luton",
  label: "Luton",
  country: "United Kingdom",
  areaLabelSingular: "Area",
  areaLabelPlural: "Areas",
  chartTitle: "Luton Crime Overview",
  note:
    "Luton uses official Community Safety Partnership and local-authority crime tables. The series is annual, based on rolling 12-month totals at the year ending each March, and it is citywide rather than neighbourhood-level.",
  sources: [
    {
      label: "ONS recorded crime data at Community Safety Partnership and local authority level",
      url: "https://www.ons.gov.uk/peoplepopulationandcommunity/crimeandjustice/datasets/recordedcrimedataatcommunitysafetypartnershiplocalauthoritylevel/current",
    },
    {
      label: "ONS population estimates detailed time series",
      url: "https://www.ons.gov.uk/peoplepopulationandcommunity/populationandmigration/populationestimates/datasets/populationestimatesforukenglandandwalesscotlandandnorthernireland%26gt",
    },
  ],
  categories: [
    {
      sourceLabels: ["Violence with injury"],
      label: "Violence with injury",
      shortLabel: "Violence w/ injury",
      color: "#facc15",
      isDefault: true,
      sortOrder: 1,
    },
    {
      sourceLabels: ["Violence without injury"],
      label: "Violence without injury",
      shortLabel: "Violence no injury",
      color: "#fde047",
      isDefault: false,
      sortOrder: 2,
    },
    {
      sourceLabels: ["Sexual offences"],
      label: "Sexual offences",
      shortLabel: "Sexual offences",
      color: "#ec4899",
      isDefault: true,
      sortOrder: 3,
    },
    {
      sourceLabels: ["Robbery"],
      label: "Robbery",
      shortLabel: "Robbery",
      color: "#f97316",
      isDefault: true,
      sortOrder: 4,
    },
    {
      sourceLabels: ["Theft from the person"],
      label: "Theft from person",
      shortLabel: "From person",
      color: "#67e8f9",
      isDefault: false,
      sortOrder: 5,
    },
    {
      sourceLabels: ["Vehicle offences"],
      label: "Vehicle offences",
      shortLabel: "Vehicle theft",
      color: "#4f46e5",
      isDefault: true,
      sortOrder: 6,
    },
    {
      sourceLabels: ["Bicycle theft"],
      label: "Bicycle theft",
      shortLabel: "Bike theft",
      color: "#22d3ee",
      isDefault: false,
      sortOrder: 7,
    },
    {
      sourceLabels: ["Shoplifting"],
      label: "Shoplifting",
      shortLabel: "Shoplifting",
      color: "#93c5fd",
      isDefault: false,
      sortOrder: 8,
    },
    {
      sourceLabels: ["All other theft offences"],
      label: "Other theft",
      shortLabel: "Other theft",
      color: "#60a5fa",
      isDefault: false,
      sortOrder: 9,
    },
    {
      sourceLabels: ["Domestic burglary", "Residential burglary"],
      label: "Residential burglary",
      shortLabel: "Res. burglary",
      color: "#ef4444",
      isDefault: true,
      sortOrder: 10,
    },
    {
      sourceLabels: ["Non-domestic burglary", "Non-residential burglary"],
      label: "Non-residential burglary",
      shortLabel: "Non-res burglary",
      color: "#f87171",
      isDefault: false,
      sortOrder: 11,
    },
    {
      sourceLabels: ["Drug offences"],
      label: "Drug offences",
      shortLabel: "Drug offences",
      color: "#22c55e",
      isDefault: true,
      sortOrder: 12,
    },
    {
      sourceLabels: ["Fraud offences"],
      label: "Fraud offences",
      shortLabel: "Fraud",
      color: "#94a3b8",
      isDefault: false,
      sortOrder: 13,
    },
    {
      sourceLabels: ["Public order offences"],
      label: "Public order offences",
      shortLabel: "Public order",
      color: "#c084fc",
      isDefault: false,
      sortOrder: 14,
    },
    {
      sourceLabels: ["Possession of weapons offences"],
      label: "Weapons possession",
      shortLabel: "Weapons",
      color: "#eab308",
      isDefault: false,
      sortOrder: 15,
    },
    {
      sourceLabels: ["Stalking and harassment"],
      label: "Stalking and harassment",
      shortLabel: "Stalking",
      color: "#a78bfa",
      isDefault: true,
      sortOrder: 16,
    },
    {
      sourceLabels: ["Criminal damage and arson"],
      label: "Criminal damage and arson",
      shortLabel: "Damage & arson",
      color: "#fb7185",
      isDefault: false,
      sortOrder: 17,
    },
    {
      sourceLabels: ["Miscellaneous crimes against society"],
      label: "Misc. crimes against society",
      shortLabel: "Misc. society",
      color: "#f59e0b",
      isDefault: false,
      sortOrder: 18,
    },
    {
      sourceLabels: ["Death or serious injury caused by illegal driving"],
      label: "Illegal-driving death or serious injury",
      shortLabel: "Illegal driving",
      color: "#fca5a5",
      isDefault: false,
      sortOrder: 19,
    },
    {
      sourceLabels: ["Homicide"],
      label: "Homicide",
      shortLabel: "Homicide",
      color: "#be123c",
      isDefault: false,
      sortOrder: 20,
    },
  ],
};

export const PARIS_LOCATION: LocationDefinition = {
  slug: "paris",
  label: "Paris",
  country: "France",
  areaLabelSingular: "Area",
  areaLabelPlural: "Areas",
  chartTitle: "Paris Crime Overview",
  note:
    "Paris uses the official communal crime base published by the French Interior Ministry and SSMSI. The figures are citywide commune totals rather than arrondissement-level series.",
  sources: [
    {
      label: "French Interior Ministry / SSMSI communal crime base",
      url: "https://www.data.gouv.fr/en/datasets/bases-statistiques-communale-departementale-et-regionale-de-la-delinquance-enregistree-par-la-police-et-la-gendarmerie-nationales/",
    },
  ],
  categories: [
    {
      sourceLabels: ["Violences physiques intrafamiliales"],
      label: "Domestic physical violence",
      shortLabel: "Domestic violence",
      color: "#fb7185",
      isDefault: false,
      sortOrder: 1,
    },
    {
      sourceLabels: ["Violences physiques hors cadre familial"],
      label: "Non-family physical violence",
      shortLabel: "Non-family violence",
      color: "#f97316",
      isDefault: true,
      sortOrder: 2,
    },
    {
      sourceLabels: ["Violences sexuelles"],
      label: "Sexual violence",
      shortLabel: "Sexual violence",
      color: "#ec4899",
      isDefault: true,
      sortOrder: 3,
    },
    {
      sourceLabels: ["Vols avec armes"],
      label: "Armed theft",
      shortLabel: "Armed theft",
      color: "#facc15",
      isDefault: true,
      sortOrder: 4,
    },
    {
      sourceLabels: ["Vols violents sans arme"],
      label: "Violent theft without weapon",
      shortLabel: "Violent theft",
      color: "#fde047",
      isDefault: true,
      sortOrder: 5,
    },
    {
      sourceLabels: ["Vols sans violence contre des personnes"],
      label: "Non-violent personal theft",
      shortLabel: "Personal theft",
      color: "#67e8f9",
      isDefault: true,
      sortOrder: 6,
    },
    {
      sourceLabels: ["Cambriolages de logement"],
      label: "Residential burglary",
      shortLabel: "Burglary",
      color: "#ef4444",
      isDefault: true,
      sortOrder: 7,
    },
    {
      sourceLabels: ["Vols de véhicule"],
      label: "Vehicle theft",
      shortLabel: "Vehicle theft",
      color: "#4f46e5",
      isDefault: true,
      sortOrder: 8,
    },
    {
      sourceLabels: ["Vols dans les véhicules"],
      label: "Theft from vehicles",
      shortLabel: "From vehicles",
      color: "#6366f1",
      isDefault: false,
      sortOrder: 9,
    },
    {
      sourceLabels: ["Vols d'accessoires sur véhicules"],
      label: "Theft of vehicle accessories",
      shortLabel: "Accessories",
      color: "#818cf8",
      isDefault: false,
      sortOrder: 10,
    },
    {
      sourceLabels: ["Destructions et dégradations volontaires"],
      label: "Criminal damage",
      shortLabel: "Criminal damage",
      color: "#fb7185",
      isDefault: false,
      sortOrder: 11,
    },
    {
      sourceLabels: ["Usage de stupéfiants"],
      label: "Drug use",
      shortLabel: "Drug use",
      color: "#22c55e",
      isDefault: false,
      sortOrder: 12,
    },
    {
      sourceLabels: ["Usage de stupéfiants (AFD)"],
      label: "Drug use (fixed-fine cases)",
      shortLabel: "Drug use AFD",
      color: "#4ade80",
      isDefault: false,
      sortOrder: 13,
    },
    {
      sourceLabels: ["Trafic de stupéfiants"],
      label: "Drug trafficking",
      shortLabel: "Drug trafficking",
      color: "#16a34a",
      isDefault: true,
      sortOrder: 14,
    },
    {
      sourceLabels: ["Escroqueries et fraudes aux moyens de paiement"],
      label: "Payment fraud and scams",
      shortLabel: "Fraud & scams",
      color: "#94a3b8",
      isDefault: false,
      sortOrder: 15,
    },
  ],
};

export const LOCATION_DEFINITIONS: LocationDefinition[] = [
  BERLIN_LOCATION,
  FRANKFURT_LOCATION,
  LONDON_LOCATION,
  LUTON_LOCATION,
  PARIS_LOCATION,
];
