export type LocationCategoryDefinition = {
  sourceLabels: string[];
  label: string;
  shortLabel: string;
  color: string;
  isDefault: boolean;
  sortOrder: number;
};

export type LocationDefinition = {
  slug: string;
  label: string;
  country: string;
  areaLabelSingular: string;
  areaLabelPlural: string;
  chartTitle: string;
  note: string;
  sources: Array<{
    label: string;
    url?: string;
  }>;
  categories: LocationCategoryDefinition[];
};

export const BERLIN_LOCATION: LocationDefinition = {
  slug: "berlin",
  label: "Berlin",
  country: "Germany",
  areaLabelSingular: "District",
  areaLabelPlural: "Districts",
  chartTitle: "Berlin Crime by District",
  note:
    "Berlin uses official Polizei Berlin atlas categories. Some categories are umbrella groups while others are nested subtypes, so the stacks are best read as comparison views rather than deduplicated totals.",
  sources: [
    {
      label: "Polizei Berlin Kriminalitätsatlas",
      url: "https://www.berlin.de/polizei/service/kriminalitaetsatlas/",
    },
    {
      label: "Polizei Berlin PKS archive and historical atlas reports",
      url: "https://www.berlin.de/polizei/verschiedenes/polizeiliche-kriminalstatistik/",
    },
    {
      label: "Current district workbook from the official atlas",
      url: "https://www.kriminalitaetsatlas.berlin.de/K-Atlas/bezirke/Fallzahlen%26HZ%202015-2024.xlsx",
    },
  ],
  categories: [
    {
      sourceLabels: ["Straftaten -insgesamt-"],
      label: "All recorded offenses",
      shortLabel: "All offenses",
      color: "#7dd3fc",
      isDefault: false,
      sortOrder: 1,
    },
    {
      sourceLabels: ["Raub"],
      label: "Robbery",
      shortLabel: "Robbery",
      color: "#f97316",
      isDefault: true,
      sortOrder: 2,
    },
    {
      sourceLabels: ["Straßenraub, Handtaschenraub"],
      label: "Street / bag robbery",
      shortLabel: "Street robbery",
      color: "#facc15",
      isDefault: true,
      sortOrder: 3,
    },
    {
      sourceLabels: ["Körperverletzungen -insgesamt-"],
      label: "All assaults",
      shortLabel: "All assaults",
      color: "#38bdf8",
      isDefault: false,
      sortOrder: 4,
    },
    {
      sourceLabels: ["Gefährl. und schwere Körperverletzung"],
      label: "Aggravated assault",
      shortLabel: "Agg. assault",
      color: "#0ea5e9",
      isDefault: true,
      sortOrder: 5,
    },
    {
      sourceLabels: ["Freiheitsberaubung, Nötigung, Bedrohung, Nachstellung"],
      label: "Coercion, threats & stalking",
      shortLabel: "Threats & stalking",
      color: "#a78bfa",
      isDefault: true,
      sortOrder: 6,
    },
    {
      sourceLabels: ["Diebstahl -insgesamt-"],
      label: "All theft",
      shortLabel: "All theft",
      color: "#60a5fa",
      isDefault: false,
      sortOrder: 7,
    },
    {
      sourceLabels: ["Diebstahl von Kraftwagen"],
      label: "Motor vehicle theft",
      shortLabel: "Vehicle theft",
      color: "#4f46e5",
      isDefault: true,
      sortOrder: 8,
    },
    {
      sourceLabels: ["Diebstahl an/aus Kfz"],
      label: "Theft from vehicles",
      shortLabel: "From vehicles",
      color: "#14b8a6",
      isDefault: false,
      sortOrder: 9,
    },
    {
      sourceLabels: ["Fahrraddiebstahl"],
      label: "Bicycle theft",
      shortLabel: "Bike theft",
      color: "#2dd4bf",
      isDefault: false,
      sortOrder: 10,
    },
    {
      sourceLabels: ["Wohnraumeinbruch"],
      label: "Residential burglary",
      shortLabel: "Burglary",
      color: "#ef4444",
      isDefault: true,
      sortOrder: 11,
    },
    {
      sourceLabels: ["Branddelikte -insgesamt-"],
      label: "All arson-related offenses",
      shortLabel: "All arson",
      color: "#fb7185",
      isDefault: false,
      sortOrder: 12,
    },
    {
      sourceLabels: ["Brandstiftung"],
      label: "Arson",
      shortLabel: "Arson",
      color: "#ec4899",
      isDefault: true,
      sortOrder: 13,
    },
    {
      sourceLabels: ["Sachbeschädigung -insgesamt-"],
      label: "All criminal damage",
      shortLabel: "All damage",
      color: "#f59e0b",
      isDefault: false,
      sortOrder: 14,
    },
    {
      sourceLabels: ["Sachbeschädigung durch Graffiti"],
      label: "Graffiti damage",
      shortLabel: "Graffiti",
      color: "#fbbf24",
      isDefault: false,
      sortOrder: 15,
    },
    {
      sourceLabels: ["Rauschgiftdelikte"],
      label: "Drug offenses",
      shortLabel: "Drug offenses",
      color: "#22c55e",
      isDefault: false,
      sortOrder: 16,
    },
    {
      sourceLabels: ["Kieztaten"],
      label: "Neighborhood offenses",
      shortLabel: "Neighborhood",
      color: "#34d399",
      isDefault: false,
      sortOrder: 17,
    },
  ],
};

export const LONDON_LOCATION: LocationDefinition = {
  slug: "london",
  label: "London",
  country: "United Kingdom",
  areaLabelSingular: "Borough",
  areaLabelPlural: "Boroughs",
  chartTitle: "London Crime by Borough",
  note:
    "London uses official Metropolitan Police recorded-crime categories aggregated to calendar years. A few categories were renamed over time, and those official aliases are merged where the dataset clearly indicates the same series.",
  sources: [
    {
      label: "MPS Recorded Crime: Geographic Breakdown dataset",
      url: "https://data.london.gov.uk/dataset/recorded_crime_summary/resource/760704bd-7d54-485c-9509-e06ff547766d",
    },
    {
      label: "ONS borough population estimates via London Datastore",
      url: "https://data.london.gov.uk/dataset/office-for-national-statistics-ons-population-estimates-borough--vd615/",
    },
    {
      label: "ONS England and Wales local-authority population workbook",
      url: "https://www.ons.gov.uk/file?uri=%2Fpeoplepopulationandcommunity%2Fpopulationandmigration%2Fpopulationestimates%2Fdatasets%2Festimatesofthepopulationforenglandandwales%2Fmid2011tomid2024detailedtimeseries%2Fmyebtablesenglandwales20112024.xlsx",
    },
  ],
  categories: [
    {
      sourceLabels: ["ROBBERY OF PERSONAL PROPERTY"],
      label: "Personal robbery",
      shortLabel: "Robbery",
      color: "#f97316",
      isDefault: true,
      sortOrder: 1,
    },
    {
      sourceLabels: ["ROBBERY OF BUSINESS PROPERTY"],
      label: "Business robbery",
      shortLabel: "Business robbery",
      color: "#fb923c",
      isDefault: false,
      sortOrder: 2,
    },
    {
      sourceLabels: ["VIOLENCE WITH INJURY"],
      label: "Violence with injury",
      shortLabel: "Violence w/ injury",
      color: "#facc15",
      isDefault: true,
      sortOrder: 3,
    },
    {
      sourceLabels: ["VIOLENCE WITHOUT INJURY"],
      label: "Violence without injury",
      shortLabel: "Violence no injury",
      color: "#fde047",
      isDefault: false,
      sortOrder: 4,
    },
    {
      sourceLabels: ["RAPE"],
      label: "Rape",
      shortLabel: "Rape",
      color: "#38bdf8",
      isDefault: true,
      sortOrder: 5,
    },
    {
      sourceLabels: ["OTHER SEXUAL OFFENCES"],
      label: "Other sexual offences",
      shortLabel: "Other sexual",
      color: "#a78bfa",
      isDefault: true,
      sortOrder: 6,
    },
    {
      sourceLabels: ["THEFT FROM THE PERSON"],
      label: "Theft from person",
      shortLabel: "From person",
      color: "#67e8f9",
      isDefault: false,
      sortOrder: 7,
    },
    {
      sourceLabels: ["THEFT OR UNAUTH TAKING OF A MOTOR VEH", "AGGRAVATED VEHICLE TAKING"],
      label: "Motor vehicle theft",
      shortLabel: "Vehicle theft",
      color: "#4f46e5",
      isDefault: true,
      sortOrder: 8,
    },
    {
      sourceLabels: ["THEFT FROM A VEHICLE", "INTERFERING WITH A MOTOR VEHICLE"],
      label: "Theft from vehicles",
      shortLabel: "From vehicles",
      color: "#6366f1",
      isDefault: false,
      sortOrder: 9,
    },
    {
      sourceLabels: ["BICYCLE THEFT"],
      label: "Bicycle theft",
      shortLabel: "Bike theft",
      color: "#22d3ee",
      isDefault: false,
      sortOrder: 10,
    },
    {
      sourceLabels: ["BURGLARY IN A DWELLING", "BURGLARY - RESIDENTIAL"],
      label: "Residential burglary",
      shortLabel: "Burglary",
      color: "#ef4444",
      isDefault: true,
      sortOrder: 11,
    },
    {
      sourceLabels: ["BURGLARY BUSINESS AND COMMUNITY", "BURGLARY NON-DWELLING"],
      label: "Non-residential burglary",
      shortLabel: "Non-res burglary",
      color: "#f87171",
      isDefault: false,
      sortOrder: 12,
    },
    {
      sourceLabels: ["CRIMINAL DAMAGE"],
      label: "Criminal damage",
      shortLabel: "Criminal damage",
      color: "#ec4899",
      isDefault: true,
      sortOrder: 13,
    },
    {
      sourceLabels: ["ARSON"],
      label: "Arson",
      shortLabel: "Arson",
      color: "#fb7185",
      isDefault: false,
      sortOrder: 14,
    },
    {
      sourceLabels: ["POSSESSION OF DRUGS"],
      label: "Drug possession",
      shortLabel: "Drug possession",
      color: "#22c55e",
      isDefault: false,
      sortOrder: 15,
    },
    {
      sourceLabels: ["TRAFFICKING OF DRUGS"],
      label: "Drug trafficking",
      shortLabel: "Drug trafficking",
      color: "#16a34a",
      isDefault: false,
      sortOrder: 16,
    },
    {
      sourceLabels: ["POSSESSION OF WEAPONS"],
      label: "Weapons possession",
      shortLabel: "Weapons",
      color: "#eab308",
      isDefault: false,
      sortOrder: 17,
    },
    {
      sourceLabels: [
        "OTHER OFFENCES PUBLIC ORDER",
        "PUBLIC FEAR ALARM OR DISTRESS",
        "RACE OR RELIGIOUS AGG PUBLIC FEAR",
        "VIOLENT DISORDER",
      ],
      label: "Public order offences",
      shortLabel: "Public order",
      color: "#c084fc",
      isDefault: false,
      sortOrder: 18,
    },
    {
      sourceLabels: ["OTHER THEFT"],
      label: "Other theft",
      shortLabel: "Other theft",
      color: "#60a5fa",
      isDefault: false,
      sortOrder: 19,
    },
    {
      sourceLabels: ["SHOPLIFTING"],
      label: "Shoplifting",
      shortLabel: "Shoplifting",
      color: "#93c5fd",
      isDefault: false,
      sortOrder: 20,
    },
  ],
};

export const FRANKFURT_LOCATION: LocationDefinition = {
  slug: "frankfurt",
  label: "Frankfurt",
  country: "Germany",
  areaLabelSingular: "Area",
  areaLabelPlural: "Areas",
  chartTitle: "Frankfurt Crime Overview",
  note:
    "Frankfurt currently uses official citywide open-data crime series from the City of Frankfurt and the Hessisches Landeskriminalamt. These categories are annual city totals rather than district-level atlas slices.",
  sources: [
    {
      label: "City of Frankfurt open data: crimes by offense type",
      url: "https://offenedaten.frankfurt.de/dcat/dataset/de-he-frankfurtam-straftaten_nach_art_der_straftat.html",
    },
    {
      label: "City of Frankfurt open data: citywide demographic indicators",
      url: "https://offenedaten.frankfurt.de/dcat/dataset/de-he-frankfurtam-demographische_kennzahlen_gesamtstaedtisch.html",
    },
  ],
  categories: [
    {
      sourceLabels: ["insgesamt"],
      label: "All recorded offenses",
      shortLabel: "All offenses",
      color: "#7dd3fc",
      isDefault: false,
      sortOrder: 1,
    },
    {
      sourceLabels: ["Straftaten gegen das Leben"],
      label: "Offenses against life",
      shortLabel: "Against life",
      color: "#fb7185",
      isDefault: false,
      sortOrder: 2,
    },
    {
      sourceLabels: ["Straftaten gegen die sexuelle Selbstbestimmung"],
      label: "Sexual offenses",
      shortLabel: "Sexual offenses",
      color: "#ec4899",
      isDefault: true,
      sortOrder: 3,
    },
    {
      sourceLabels: ["Rohheitsdelikte und Straftaten gegen die persönliche Freiheit"],
      label: "Violence and personal freedom",
      shortLabel: "Violence & freedom",
      color: "#f97316",
      isDefault: true,
      sortOrder: 4,
    },
    {
      sourceLabels: ["Eigentumsdelikte"],
      label: "Property offenses",
      shortLabel: "Property",
      color: "#38bdf8",
      isDefault: false,
      sortOrder: 5,
    },
    {
      sourceLabels: ["ohne erschwerende Umstände"],
      label: "Simple theft and related offenses",
      shortLabel: "Simple theft",
      color: "#0ea5e9",
      isDefault: true,
      sortOrder: 6,
    },
    {
      sourceLabels: ["unter erschwerenden Umständen"],
      label: "Aggravated theft and related offenses",
      shortLabel: "Aggr. theft",
      color: "#4f46e5",
      isDefault: true,
      sortOrder: 7,
    },
    {
      sourceLabels: ["Vermögens- und Fälschungsdelikte"],
      label: "Financial and forgery offenses",
      shortLabel: "Financial & forgery",
      color: "#a78bfa",
      isDefault: true,
      sortOrder: 8,
    },
    {
      sourceLabels: ["sonstige Straftatbestände nach dem Strafgesetzbuch"],
      label: "Other criminal code offenses",
      shortLabel: "Other criminal code",
      color: "#f59e0b",
      isDefault: false,
      sortOrder: 9,
    },
    {
      sourceLabels: ["strafrechtliche Nebengesetze"],
      label: "Ancillary criminal-law offenses",
      shortLabel: "Ancillary laws",
      color: "#22c55e",
      isDefault: false,
      sortOrder: 10,
    },
  ],
};

export const LUTON_LOCATION: LocationDefinition = {
  slug: "luton",
  label: "Luton",
  country: "United Kingdom",
  areaLabelSingular: "Area",
  areaLabelPlural: "Areas",
  chartTitle: "Luton Crime Overview",
  note:
    "Luton uses official Community Safety Partnership and local-authority crime tables. The series is annual, based on rolling 12-month totals at the year ending each March, and it is citywide rather than neighbourhood-level.",
  sources: [
    {
      label: "ONS recorded crime data at Community Safety Partnership and local authority level",
      url: "https://www.ons.gov.uk/peoplepopulationandcommunity/crimeandjustice/datasets/recordedcrimedataatcommunitysafetypartnershiplocalauthoritylevel/current",
    },
    {
      label: "ONS population estimates detailed time series",
      url: "https://www.ons.gov.uk/peoplepopulationandcommunity/populationandmigration/populationestimates/datasets/populationestimatesforukenglandandwalesscotlandandnorthernireland%26gt",
    },
  ],
  categories: [
    {
      sourceLabels: ["Violence with injury"],
      label: "Violence with injury",
      shortLabel: "Violence w/ injury",
      color: "#facc15",
      isDefault: true,
      sortOrder: 1,
    },
    {
      sourceLabels: ["Violence without injury"],
      label: "Violence without injury",
      shortLabel: "Violence no injury",
      color: "#fde047",
      isDefault: false,
      sortOrder: 2,
    },
    {
      sourceLabels: ["Sexual offences"],
      label: "Sexual offences",
      shortLabel: "Sexual offences",
      color: "#ec4899",
      isDefault: true,
      sortOrder: 3,
    },
    {
      sourceLabels: ["Robbery"],
      label: "Robbery",
      shortLabel: "Robbery",
      color: "#f97316",
      isDefault: true,
      sortOrder: 4,
    },
    {
      sourceLabels: ["Theft from the person"],
      label: "Theft from person",
      shortLabel: "From person",
      color: "#67e8f9",
      isDefault: false,
      sortOrder: 5,
    },
    {
      sourceLabels: ["Vehicle offences"],
      label: "Vehicle offences",
      shortLabel: "Vehicle theft",
      color: "#4f46e5",
      isDefault: true,
      sortOrder: 6,
    },
    {
      sourceLabels: ["Bicycle theft"],
      label: "Bicycle theft",
      shortLabel: "Bike theft",
      color: "#22d3ee",
      isDefault: false,
      sortOrder: 7,
    },
    {
      sourceLabels: ["Shoplifting"],
      label: "Shoplifting",
      shortLabel: "Shoplifting",
      color: "#93c5fd",
      isDefault: false,
      sortOrder: 8,
    },
    {
      sourceLabels: ["All other theft offences"],
      label: "Other theft",
      shortLabel: "Other theft",
      color: "#60a5fa",
      isDefault: false,
      sortOrder: 9,
    },
    {
      sourceLabels: ["Domestic burglary", "Residential burglary"],
      label: "Residential burglary",
      shortLabel: "Res. burglary",
      color: "#ef4444",
      isDefault: true,
      sortOrder: 10,
    },
    {
      sourceLabels: ["Non-domestic burglary", "Non-residential burglary"],
      label: "Non-residential burglary",
      shortLabel: "Non-res burglary",
      color: "#f87171",
      isDefault: false,
      sortOrder: 11,
    },
    {
      sourceLabels: ["Drug offences"],
      label: "Drug offences",
      shortLabel: "Drug offences",
      color: "#22c55e",
      isDefault: true,
      sortOrder: 12,
    },
    {
      sourceLabels: ["Fraud offences"],
      label: "Fraud offences",
      shortLabel: "Fraud",
      color: "#94a3b8",
      isDefault: false,
      sortOrder: 13,
    },
    {
      sourceLabels: ["Public order offences"],
      label: "Public order offences",
      shortLabel: "Public order",
      color: "#c084fc",
      isDefault: false,
      sortOrder: 14,
    },
    {
      sourceLabels: ["Possession of weapons offences"],
      label: "Weapons possession",
      shortLabel: "Weapons",
      color: "#eab308",
      isDefault: false,
      sortOrder: 15,
    },
    {
      sourceLabels: ["Stalking and harassment"],
      label: "Stalking and harassment",
      shortLabel: "Stalking",
      color: "#a78bfa",
      isDefault: true,
      sortOrder: 16,
    },
    {
      sourceLabels: ["Criminal damage and arson"],
      label: "Criminal damage and arson",
      shortLabel: "Damage & arson",
      color: "#fb7185",
      isDefault: false,
      sortOrder: 17,
    },
    {
      sourceLabels: ["Miscellaneous crimes against society"],
      label: "Misc. crimes against society",
      shortLabel: "Misc. society",
      color: "#f59e0b",
      isDefault: false,
      sortOrder: 18,
    },
    {
      sourceLabels: ["Death or serious injury caused by illegal driving"],
      label: "Illegal-driving death or serious injury",
      shortLabel: "Illegal driving",
      color: "#fca5a5",
      isDefault: false,
      sortOrder: 19,
    },
    {
      sourceLabels: ["Homicide"],
      label: "Homicide",
      shortLabel: "Homicide",
      color: "#be123c",
      isDefault: false,
      sortOrder: 20,
    },
  ],
};

export const PARIS_LOCATION: LocationDefinition = {
  slug: "paris",
  label: "Paris",
  country: "France",
  areaLabelSingular: "Area",
  areaLabelPlural: "Areas",
  chartTitle: "Paris Crime Overview",
  note:
    "Paris uses the official communal crime base published by the French Interior Ministry and SSMSI. The figures are citywide commune totals rather than arrondissement-level series.",
  sources: [
    {
      label: "French Interior Ministry / SSMSI communal crime base",
      url: "https://www.data.gouv.fr/en/datasets/bases-statistiques-communale-departementale-et-regionale-de-la-delinquance-enregistree-par-la-police-et-la-gendarmerie-nationales/",
    },
  ],
  categories: [
    {
      sourceLabels: ["Violences physiques intrafamiliales"],
      label: "Domestic physical violence",
      shortLabel: "Domestic violence",
      color: "#fb7185",
      isDefault: false,
      sortOrder: 1,
    },
    {
      sourceLabels: ["Violences physiques hors cadre familial"],
      label: "Non-family physical violence",
      shortLabel: "Non-family violence",
      color: "#f97316",
      isDefault: true,
      sortOrder: 2,
    },
    {
      sourceLabels: ["Violences sexuelles"],
      label: "Sexual violence",
      shortLabel: "Sexual violence",
      color: "#ec4899",
      isDefault: true,
      sortOrder: 3,
    },
    {
      sourceLabels: ["Vols avec armes"],
      label: "Armed theft",
      shortLabel: "Armed theft",
      color: "#facc15",
      isDefault: true,
      sortOrder: 4,
    },
    {
      sourceLabels: ["Vols violents sans arme"],
      label: "Violent theft without weapon",
      shortLabel: "Violent theft",
      color: "#fde047",
      isDefault: true,
      sortOrder: 5,
    },
    {
      sourceLabels: ["Vols sans violence contre des personnes"],
      label: "Non-violent personal theft",
      shortLabel: "Personal theft",
      color: "#67e8f9",
      isDefault: true,
      sortOrder: 6,
    },
    {
      sourceLabels: ["Cambriolages de logement"],
      label: "Residential burglary",
      shortLabel: "Burglary",
      color: "#ef4444",
      isDefault: true,
      sortOrder: 7,
    },
    {
      sourceLabels: ["Vols de véhicule"],
      label: "Vehicle theft",
      shortLabel: "Vehicle theft",
      color: "#4f46e5",
      isDefault: true,
      sortOrder: 8,
    },
    {
      sourceLabels: ["Vols dans les véhicules"],
      label: "Theft from vehicles",
      shortLabel: "From vehicles",
      color: "#6366f1",
      isDefault: false,
      sortOrder: 9,
    },
    {
      sourceLabels: ["Vols d'accessoires sur véhicules"],
      label: "Theft of vehicle accessories",
      shortLabel: "Accessories",
      color: "#818cf8",
      isDefault: false,
      sortOrder: 10,
    },
    {
      sourceLabels: ["Destructions et dégradations volontaires"],
      label: "Criminal damage",
      shortLabel: "Criminal damage",
      color: "#fb7185",
      isDefault: false,
      sortOrder: 11,
    },
    {
      sourceLabels: ["Usage de stupéfiants"],
      label: "Drug use",
      shortLabel: "Drug use",
      color: "#22c55e",
      isDefault: false,
      sortOrder: 12,
    },
    {
      sourceLabels: ["Usage de stupéfiants (AFD)"],
      label: "Drug use (fixed-fine cases)",
      shortLabel: "Drug use AFD",
      color: "#4ade80",
      isDefault: false,
      sortOrder: 13,
    },
    {
      sourceLabels: ["Trafic de stupéfiants"],
      label: "Drug trafficking",
      shortLabel: "Drug trafficking",
      color: "#16a34a",
      isDefault: true,
      sortOrder: 14,
    },
    {
      sourceLabels: ["Escroqueries et fraudes aux moyens de paiement"],
      label: "Payment fraud and scams",
      shortLabel: "Fraud & scams",
      color: "#94a3b8",
      isDefault: false,
      sortOrder: 15,
    },
  ],
};

export const MUNICH_LOCATION: LocationDefinition = {
  slug: "munich",
  label: "Munich",
  country: "Germany",
  areaLabelSingular: "Area",
  areaLabelPlural: "Areas",
  chartTitle: "Munich Crime Overview",
  note:
    "Munich uses official city statistics publications sourced from Polizeipräsidium München. The app extracts a stable cross-year subset of annual citywide recorded-crime categories from the official summary tables; no sub-city breakdown is wired yet.",
  sources: [
    {
      label: "Landeshauptstadt München: safety and crime statistics archive",
      url: "https://stadt.muenchen.de/infos/statistik-sicherheit.html",
    },
  ],
  categories: [
    {
      sourceLabels: ["Straftaten insgesamt"],
      label: "All recorded offenses",
      shortLabel: "All offenses",
      color: "#7dd3fc",
      isDefault: false,
      sortOrder: 1,
    },
    {
      sourceLabels: ["Straftaten gegen die sexuelle Selbstbestimmung"],
      label: "Sexual offenses",
      shortLabel: "Sexual offenses",
      color: "#ec4899",
      isDefault: true,
      sortOrder: 2,
    },
    {
      sourceLabels: ["Vergewaltigung"],
      label: "Rape",
      shortLabel: "Rape",
      color: "#f472b6",
      isDefault: false,
      sortOrder: 3,
    },
    {
      sourceLabels: ["Raub, räuberische Erpressung und räuberischer Angriff auf Kraftfahrer*innen"],
      label: "Robbery",
      shortLabel: "Robbery",
      color: "#f97316",
      isDefault: true,
      sortOrder: 4,
    },
    {
      sourceLabels: ["Diebstahl insgesamt"],
      label: "Theft",
      shortLabel: "Theft",
      color: "#facc15",
      isDefault: true,
      sortOrder: 5,
    },
    {
      sourceLabels: ["Diebstahl von Kraftwagen"],
      label: "Vehicle theft",
      shortLabel: "Vehicle theft",
      color: "#4f46e5",
      isDefault: true,
      sortOrder: 6,
    },
    {
      sourceLabels: ["Diebstahl von Fahrrädern"],
      label: "Bicycle theft",
      shortLabel: "Bike theft",
      color: "#38bdf8",
      isDefault: false,
      sortOrder: 7,
    },
    {
      sourceLabels: ["Betrug und Veruntreuung"],
      label: "Fraud and embezzlement",
      shortLabel: "Fraud & embezzlement",
      color: "#94a3b8",
      isDefault: false,
      sortOrder: 8,
    },
    {
      sourceLabels: ["Rauschgiftdelikte"],
      label: "Drug offenses",
      shortLabel: "Drug offenses",
      color: "#22c55e",
      isDefault: true,
      sortOrder: 9,
    },
  ],
};

export const HAMBURG_LOCATION: LocationDefinition = {
  slug: "hamburg",
  label: "Hamburg",
  country: "Germany",
  areaLabelSingular: "Area",
  areaLabelPlural: "Areas",
  chartTitle: "Hamburg Crime Overview",
  note:
    "Hamburg uses official Polizeiliche Kriminalstatistik yearbooks published by the Hamburg police. The app currently shows a stable citywide subset of annual recorded-crime counts from the official PKS comparison tables.",
  sources: [
    {
      label: "Polizei Hamburg: Polizeiliche Kriminalstatistik service page",
      url: "https://www.polizei.hamburg/services/polizeiliche-kriminalstatistik",
    },
    {
      label: "Polizei Hamburg PKS yearbook 2024",
      url: "https://www.polizei.hamburg/resource/blob/1053710/30efad000cc60586a22280031dad1ea0/pks-2024-jahrbuch-do-data.pdf",
    },
  ],
  categories: [
    {
      sourceLabels: ["Straftaten insgesamt"],
      label: "All recorded offenses",
      shortLabel: "All offenses",
      color: "#7dd3fc",
      isDefault: false,
      sortOrder: 1,
    },
    {
      sourceLabels: ["Straftaten gegen die sexuelle Selbstbestimmung"],
      label: "Sexual offenses",
      shortLabel: "Sexual offenses",
      color: "#ec4899",
      isDefault: true,
      sortOrder: 2,
    },
    {
      sourceLabels: ["Vergewaltigung, sexuelle Nötigung und sexuelle Übergriffe im besonders schweren Fall"],
      label: "Rape and severe sexual assault",
      shortLabel: "Rape / severe assault",
      color: "#f472b6",
      isDefault: false,
      sortOrder: 3,
    },
    {
      sourceLabels: ["Raub, räuberische Erpressung, räuberischer Angriff auf Kraftfahrer"],
      label: "Robbery",
      shortLabel: "Robbery",
      color: "#f97316",
      isDefault: true,
      sortOrder: 4,
    },
    {
      sourceLabels: ["Körperverletzung insgesamt"],
      label: "All assaults",
      shortLabel: "All assaults",
      color: "#fde047",
      isDefault: false,
      sortOrder: 5,
    },
    {
      sourceLabels: ["Gefährliche und schwere Körperverletzung"],
      label: "Aggravated assault",
      shortLabel: "Agg. assault",
      color: "#fb923c",
      isDefault: true,
      sortOrder: 6,
    },
    {
      sourceLabels: ["Gewaltkriminalität"],
      label: "Violent crime",
      shortLabel: "Violent crime",
      color: "#f59e0b",
      isDefault: false,
      sortOrder: 7,
    },
    {
      sourceLabels: ["Diebstahl insgesamt"],
      label: "Theft",
      shortLabel: "Theft",
      color: "#facc15",
      isDefault: true,
      sortOrder: 8,
    },
    {
      sourceLabels: ["Wohnungseinbruchdiebstahl"],
      label: "Residential burglary",
      shortLabel: "Burglary",
      color: "#ef4444",
      isDefault: false,
      sortOrder: 9,
    },
    {
      sourceLabels: ["Diebstahl/unbefugter Gebrauch eines Kraftwagens"],
      label: "Vehicle theft",
      shortLabel: "Vehicle theft",
      color: "#4f46e5",
      isDefault: true,
      sortOrder: 10,
    },
    {
      sourceLabels: ["Diebstahl insgesamt an/aus Kraftfahrzeugen"],
      label: "Theft from vehicles",
      shortLabel: "From vehicles",
      color: "#14b8a6",
      isDefault: false,
      sortOrder: 11,
    },
    {
      sourceLabels: ["Diebstahl insgesamt von Fahrrädern"],
      label: "Bicycle theft",
      shortLabel: "Bike theft",
      color: "#38bdf8",
      isDefault: false,
      sortOrder: 12,
    },
    {
      sourceLabels: ["Taschendiebstahl"],
      label: "Pickpocketing",
      shortLabel: "Pickpocketing",
      color: "#67e8f9",
      isDefault: false,
      sortOrder: 13,
    },
    {
      sourceLabels: ["Betrug"],
      label: "Fraud",
      shortLabel: "Fraud",
      color: "#94a3b8",
      isDefault: false,
      sortOrder: 14,
    },
  ],
};

export const BARCELONA_LOCATION: LocationDefinition = {
  slug: "barcelona",
  label: "Barcelona",
  country: "Spain",
  areaLabelSingular: "Area",
  areaLabelPlural: "Areas",
  chartTitle: "Barcelona Crime Overview",
  note:
    "Barcelona uses official Spanish Interior Ministry annual crime-balance releases for the municipality of Barcelona. The app combines the verified year-end municipal tables published by the ministry; rate-per-100k is not shown because this source path does not bundle a comparable municipal population series in the same extract.",
  sources: [
    {
      label: "Spanish Interior Ministry balances and reports archive",
      url: "https://www.interior.gob.es/opencms/es/prensa/balances-e-informes/",
    },
    {
      label: "Spanish Interior Ministry crime statistics portal publications",
      url: "https://estadisticasdecriminalidad.ses.mir.es/publico/portalestadistico/publicaciones.html",
    },
  ],
  categories: [
    {
      sourceLabels: ["III. TOTAL CRIMINALIDAD", "TOTAL INFRACCIONES PENALES", "1.-DELITOS Y FALTAS (EU)"],
      label: "All recorded offenses",
      shortLabel: "All offenses",
      color: "#7dd3fc",
      isDefault: false,
      sortOrder: 1,
    },
    {
      sourceLabels: ["I. CRIMINALIDAD CONVENCIONAL"],
      label: "Conventional crime",
      shortLabel: "Conventional",
      color: "#93c5fd",
      isDefault: false,
      sortOrder: 2,
    },
    {
      sourceLabels: ["3. Delitos graves y menos graves de lesiones y riña tumultuaria", "3.-Delitos graves y menos graves de lesiones y riña tumultuaria"],
      label: "Assaults and disorder",
      shortLabel: "Assaults",
      color: "#f97316",
      isDefault: false,
      sortOrder: 3,
    },
    {
      sourceLabels: ["5. Delitos contra la libertad sexual", "5.-Delitos contra la libertad e indemnidad sexual"],
      label: "Sexual offenses",
      shortLabel: "Sexual offenses",
      color: "#ec4899",
      isDefault: true,
      sortOrder: 4,
    },
    {
      sourceLabels: ["5.1.-Agresión sexual con penetración", "5.1.-Agresion sexual con penetracion"],
      label: "Penetrative sexual assault",
      shortLabel: "Penetrative assault",
      color: "#f472b6",
      isDefault: false,
      sortOrder: 5,
    },
    {
      sourceLabels: [
        "5.2.-Resto de delitos contra la libertad sexual",
        "5.2.-Resto de delitos contra la libertad e indemnidad sexual",
      ],
      label: "Other sexual offenses",
      shortLabel: "Other sexual",
      color: "#a78bfa",
      isDefault: false,
      sortOrder: 6,
    },
    {
      sourceLabels: ["6. Robos con violencia e intimidación", "6.-Robos con violencia e intimidacion", "3.-ROBO CON VIOLENCIA E INTIMIDACION (EU)"],
      label: "Robbery with violence or intimidation",
      shortLabel: "Robbery",
      color: "#fb923c",
      isDefault: true,
      sortOrder: 7,
    },
    {
      sourceLabels: [
        "7. Robos con fuerza en domicilios, establecimientos y otras instalaciones",
        "7.- Robos con fuerza en domicilios, establecimientos y otras instalaciones",
        "4.-ROBOS CON FUERZA EN DOMICILIOS (EU)",
      ],
      label: "Burglary and forced-entry theft",
      shortLabel: "Burglary",
      color: "#ef4444",
      isDefault: true,
      sortOrder: 8,
    },
    {
      sourceLabels: ["7.1.-Robos con fuerza en domicilios"],
      label: "Residential burglary",
      shortLabel: "Res. burglary",
      color: "#f87171",
      isDefault: false,
      sortOrder: 9,
    },
    {
      sourceLabels: ["8. Hurtos", "8.-Hurtos"],
      label: "Theft",
      shortLabel: "Theft",
      color: "#facc15",
      isDefault: true,
      sortOrder: 10,
    },
    {
      sourceLabels: ["9. Sustracciones de vehículos", "9.-Sustracciones de vehiculos", "5.-SUSTRACCION VEHICULOS A MOTOR (EU)"],
      label: "Vehicle theft",
      shortLabel: "Vehicle theft",
      color: "#4f46e5",
      isDefault: true,
      sortOrder: 11,
    },
    {
      sourceLabels: ["10. Tráfico de drogas", "10.-Trafico de drogas", "6.-TRAFICO DE DROGAS (EU)"],
      label: "Drug trafficking",
      shortLabel: "Drug trafficking",
      color: "#22c55e",
      isDefault: true,
      sortOrder: 12,
    },
    {
      sourceLabels: ["11. Resto de criminalidad CONVENCIONAL"],
      label: "Other conventional crime",
      shortLabel: "Other conventional",
      color: "#94a3b8",
      isDefault: false,
      sortOrder: 13,
    },
    {
      sourceLabels: ["II. CIBERCRIMINALIDAD (infracciones penales cometidas en/por medio ciber)"],
      label: "Cybercrime",
      shortLabel: "Cybercrime",
      color: "#38bdf8",
      isDefault: false,
      sortOrder: 14,
    },
    {
      sourceLabels: ["12.-Estafas informáticas"],
      label: "Online fraud",
      shortLabel: "Online fraud",
      color: "#67e8f9",
      isDefault: true,
      sortOrder: 15,
    },
    {
      sourceLabels: ["13.-Otros ciberdelitos"],
      label: "Other cybercrime",
      shortLabel: "Other cyber",
      color: "#60a5fa",
      isDefault: false,
      sortOrder: 16,
    },
  ],
};

export const VALENCIA_LOCATION: LocationDefinition = {
  ...BARCELONA_LOCATION,
  slug: "valencia",
  label: "Valencia",
  chartTitle: "Valencia Crime Overview",
};

export const TOKYO_LOCATION: LocationDefinition = {
  slug: "tokyo",
  label: "Tokyo",
  country: "Japan",
  areaLabelSingular: "Area",
  areaLabelPlural: "Areas",
  chartTitle: "Tokyo Crime by Area",
  note:
    "Tokyo uses the official Tokyo Statistical Yearbook crime table. The source is published at police-station level and is aggregated here to district and ward totals; rate-per-100k is not shown because this path does not currently bundle a matching population series in the same extract.",
  sources: [
    {
      label: "Tokyo Statistical Yearbook: criminal offenses known to the police by type of crime and police station",
      url: "https://www.toukei.metro.tokyo.lg.jp/tnenkan/2023/tn23qv201000.csv",
    },
  ],
  categories: [
    {
      sourceLabels: ["総数 Total"],
      label: "All recorded offenses",
      shortLabel: "All offenses",
      color: "#7dd3fc",
      isDefault: false,
      sortOrder: 1,
    },
    {
      sourceLabels: ["凶悪犯 Felonious offenses／殺人 Homicide"],
      label: "Homicide",
      shortLabel: "Homicide",
      color: "#be123c",
      isDefault: false,
      sortOrder: 2,
    },
    {
      sourceLabels: ["凶悪犯 Felonious offenses／不同意性交等 Penetrative sexual assault， etc. 3)"],
      label: "Penetrative sexual assault",
      shortLabel: "Sexual assault",
      color: "#f472b6",
      isDefault: true,
      sortOrder: 3,
    },
    {
      sourceLabels: [
        "凶悪犯 Felonious offenses／侵入強盗 Breaking & entering／Robbery／殺人 Homicide",
        "凶悪犯 Felonious offenses／侵入強盗 Breaking & entering／Robbery／傷人 Bodily injury",
        "凶悪犯 Felonious offenses／侵入強盗 Breaking & entering／Robbery／不同意性交等 Penetrative sexual assault， etc. 3)",
        "凶悪犯 Felonious offenses／侵入強盗 Breaking & entering／Robbery／普通 Others",
        "凶悪犯 Felonious offenses／非侵入強盗 Robbery without breaking and entering／殺人 Homicide",
        "凶悪犯 Felonious offenses／非侵入強盗 Robbery without breaking and entering／傷人 Bodily injury",
        "凶悪犯 Felonious offenses／非侵入強盗 Robbery without breaking and entering／不同意性交等 Penetrative sexual assault， etc. 3)",
        "凶悪犯 Felonious offenses／非侵入強盗 Robbery without breaking and entering／普通 Others",
      ],
      label: "Robbery",
      shortLabel: "Robbery",
      color: "#f97316",
      isDefault: true,
      sortOrder: 4,
    },
    {
      sourceLabels: ["粗暴犯 Violent offenses／暴行 Violence"],
      label: "Violence",
      shortLabel: "Violence",
      color: "#facc15",
      isDefault: false,
      sortOrder: 5,
    },
    {
      sourceLabels: ["粗暴犯 Violent offenses／傷害 Bodily injury"],
      label: "Bodily injury",
      shortLabel: "Bodily injury",
      color: "#38bdf8",
      isDefault: true,
      sortOrder: 6,
    },
    {
      sourceLabels: ["粗暴犯 Violent offenses／脅迫 Intimidation"],
      label: "Intimidation",
      shortLabel: "Intimidation",
      color: "#a78bfa",
      isDefault: false,
      sortOrder: 7,
    },
    {
      sourceLabels: ["粗暴犯 Violent offenses／恐喝 Extortion"],
      label: "Extortion",
      shortLabel: "Extortion",
      color: "#c084fc",
      isDefault: false,
      sortOrder: 8,
    },
    {
      sourceLabels: ["窃盗犯 Larcenous offenses／侵入窃盗 Breaking & entering／theft"],
      label: "Breaking-and-entering theft",
      shortLabel: "Breaking-entry",
      color: "#ef4444",
      isDefault: false,
      sortOrder: 9,
    },
    {
      sourceLabels: ["窃盗犯 Larcenous offenses／非侵入窃盗 Theft without breaking and entering"],
      label: "Theft without breaking and entering",
      shortLabel: "Theft",
      color: "#60a5fa",
      isDefault: true,
      sortOrder: 10,
    },
    {
      sourceLabels: ["知能犯 Intellectual offenses／詐欺 Fraud"],
      label: "Fraud",
      shortLabel: "Fraud",
      color: "#94a3b8",
      isDefault: false,
      sortOrder: 11,
    },
    {
      sourceLabels: ["知能犯 Intellectual offenses／横領 Embezzlement"],
      label: "Embezzlement",
      shortLabel: "Embezzlement",
      color: "#64748b",
      isDefault: false,
      sortOrder: 12,
    },
    {
      sourceLabels: ["知能犯 Intellectual offenses／偽造 Counterfeiting"],
      label: "Counterfeiting",
      shortLabel: "Counterfeiting",
      color: "#818cf8",
      isDefault: false,
      sortOrder: 13,
    },
    {
      sourceLabels: ["風俗犯 Moral offenses／わいせつ Indecency"],
      label: "Indecency offenses",
      shortLabel: "Indecency",
      color: "#ec4899",
      isDefault: false,
      sortOrder: 14,
    },
    {
      sourceLabels: ["凶悪犯 Felonious offenses／放火 Arson"],
      label: "Arson",
      shortLabel: "Arson",
      color: "#fb7185",
      isDefault: false,
      sortOrder: 15,
    },
    {
      sourceLabels: ["その他 Others／器物損壊等 Damage or destruction of structure， etc."],
      label: "Criminal damage",
      shortLabel: "Criminal damage",
      color: "#f59e0b",
      isDefault: false,
      sortOrder: 16,
    },
  ],
};

export const SAO_PAULO_LOCATION: LocationDefinition = {
  slug: "sao-paulo",
  label: "São Paulo",
  country: "Brazil",
  areaLabelSingular: "Area",
  areaLabelPlural: "Areas",
  chartTitle: "São Paulo Crime Overview",
  note:
    "São Paulo uses the official São Paulo state public-security quarterly statistical tables, restricted here to the year-end fourth-quarter releases and the citywide Capital column so the series remains annual and comparable across years. Rate-per-100k is not shown because this source path does not currently bundle a matching city population series in the same extract.",
  sources: [
    {
      label: "São Paulo State Public Security Secretariat quarterly statistics archive",
      url: "https://www.ssp.sp.gov.br/estatistica/dados-mensais",
    },
  ],
  categories: [
    {
      sourceLabels: ["Total de delitos"],
      label: "All recorded offenses",
      shortLabel: "All offenses",
      color: "#7dd3fc",
      isDefault: false,
      sortOrder: 1,
    },
    {
      sourceLabels: ["Homicídio doloso", "Homic�dio doloso"],
      label: "Homicide",
      shortLabel: "Homicide",
      color: "#be123c",
      isDefault: false,
      sortOrder: 2,
    },
    {
      sourceLabels: ["Tentativa de homicídio", "Tentativa de homic�dio"],
      label: "Attempted homicide",
      shortLabel: "Attempted homicide",
      color: "#f97316",
      isDefault: false,
      sortOrder: 3,
    },
    {
      sourceLabels: ["Estupro TOTAL (17)", "Estupro TOTAL(17)"],
      label: "Sexual offenses",
      shortLabel: "Sexual offenses",
      color: "#ec4899",
      isDefault: true,
      sortOrder: 4,
    },
    {
      sourceLabels: ["Estupro"],
      label: "Rape",
      shortLabel: "Rape",
      color: "#f472b6",
      isDefault: false,
      sortOrder: 5,
    },
    {
      sourceLabels: ["Estupro de Vulnerável", "Estupro de Vulner�vel"],
      label: "Rape of vulnerable persons",
      shortLabel: "Vulnerable rape",
      color: "#a78bfa",
      isDefault: false,
      sortOrder: 6,
    },
    {
      sourceLabels: ["Lesão corporal dolosa", "Les�o corporal dolosa"],
      label: "Assault",
      shortLabel: "Assault",
      color: "#38bdf8",
      isDefault: true,
      sortOrder: 7,
    },
    {
      sourceLabels: ["Extorsão mediante seqüestro (5)", "Extors�o mediante seq�estro (5)"],
      label: "Kidnapping and extortion",
      shortLabel: "Kidnap/extortion",
      color: "#c084fc",
      isDefault: false,
      sortOrder: 8,
    },
    {
      sourceLabels: ["Tráfico de entorpecentes", "Tr�fico de entorpecentes"],
      label: "Drug trafficking",
      shortLabel: "Drug trafficking",
      color: "#22c55e",
      isDefault: true,
      sortOrder: 9,
    },
    {
      sourceLabels: ["Roubo - outros TOTAL(6)"],
      label: "Robbery",
      shortLabel: "Robbery",
      color: "#fb923c",
      isDefault: true,
      sortOrder: 10,
    },
    {
      sourceLabels: ["Roubo de veículos", "Roubo de ve�culos"],
      label: "Vehicle robbery",
      shortLabel: "Vehicle robbery",
      color: "#6366f1",
      isDefault: false,
      sortOrder: 11,
    },
    {
      sourceLabels: ["Furto - outros"],
      label: "Theft",
      shortLabel: "Theft",
      color: "#facc15",
      isDefault: true,
      sortOrder: 12,
    },
    {
      sourceLabels: ["Furto de veículos", "Furto de ve�culos"],
      label: "Vehicle theft",
      shortLabel: "Vehicle theft",
      color: "#4f46e5",
      isDefault: true,
      sortOrder: 13,
    },
  ],
};

export const ROME_LOCATION: LocationDefinition = {
  slug: "rome",
  label: "Rome",
  country: "Italy",
  areaLabelSingular: "Area",
  areaLabelPlural: "Areas",
  chartTitle: "Rome Crime Overview",
  note:
    "Rome uses official Roma Capitale urban-security workbooks. These are annual citywide totals rather than neighborhood slices, with yearly offense-type tables and resident population used for the rate view.",
  sources: [
    {
      label: "Roma Capitale statistics: legality and public safety",
      url: "https://www.comune.roma.it/web/it/roma-statistica-legalita-e-sicurezza1.page",
    },
  ],
  categories: [
    {
      sourceLabels: ["All recorded offenses"],
      label: "All recorded offenses",
      shortLabel: "All offenses",
      color: "#7dd3fc",
      isDefault: false,
      sortOrder: 1,
    },
    {
      sourceLabels: ["Furti"],
      label: "Theft",
      shortLabel: "Theft",
      color: "#facc15",
      isDefault: true,
      sortOrder: 2,
    },
    {
      sourceLabels: ["Rapine"],
      label: "Robbery",
      shortLabel: "Robbery",
      color: "#f97316",
      isDefault: true,
      sortOrder: 3,
    },
    {
      sourceLabels: ["Violenze sessuali"],
      label: "Sexual violence",
      shortLabel: "Sexual violence",
      color: "#ec4899",
      isDefault: true,
      sortOrder: 4,
    },
    {
      sourceLabels: ["Altri delitti a sfondo sessuale"],
      label: "Other sexual offenses",
      shortLabel: "Other sexual",
      color: "#a78bfa",
      isDefault: false,
      sortOrder: 5,
    },
    {
      sourceLabels: ["Stupefacenti"],
      label: "Drug offenses",
      shortLabel: "Drug offenses",
      color: "#22c55e",
      isDefault: true,
      sortOrder: 6,
    },
    {
      sourceLabels: ["Delitti, truffe e frodi informatiche"],
      label: "Cyber fraud",
      shortLabel: "Cyber fraud",
      color: "#38bdf8",
      isDefault: true,
      sortOrder: 7,
    },
    {
      sourceLabels: ["Danneggiamenti"],
      label: "Criminal damage",
      shortLabel: "Criminal damage",
      color: "#fb7185",
      isDefault: true,
      sortOrder: 8,
    },
    {
      sourceLabels: ["Percosse, lesioni"],
      label: "Assaults",
      shortLabel: "Assaults",
      color: "#fde047",
      isDefault: false,
      sortOrder: 9,
    },
    {
      sourceLabels: ["Minacce, ingiurie"],
      label: "Threats and insults",
      shortLabel: "Threats",
      color: "#c084fc",
      isDefault: false,
      sortOrder: 10,
    },
    {
      sourceLabels: ["Contrabbando, contraffazione, ricettazione, riciclaggio"],
      label: "Counterfeit, fencing and laundering",
      shortLabel: "Counterfeit & laundering",
      color: "#94a3b8",
      isDefault: false,
      sortOrder: 11,
    },
    {
      sourceLabels: ["Usura ed estorsione"],
      label: "Usury and extortion",
      shortLabel: "Extortion",
      color: "#f59e0b",
      isDefault: false,
      sortOrder: 12,
    },
    {
      sourceLabels: ["Omicidi"],
      label: "Homicide",
      shortLabel: "Homicide",
      color: "#be123c",
      isDefault: false,
      sortOrder: 13,
    },
    {
      sourceLabels: ["Tentati omicidi"],
      label: "Attempted homicide",
      shortLabel: "Attempted homicide",
      color: "#fda4af",
      isDefault: false,
      sortOrder: 14,
    },
  ],
};

export const MILAN_LOCATION: LocationDefinition = {
  slug: "milan",
  label: "Milan",
  country: "Italy",
  areaLabelSingular: "Area",
  areaLabelPlural: "Areas",
  chartTitle: "Milan Crime Overview",
  note:
    "Milan uses official Comune di Milano open-data series for reported crimes and official resident-population series for the rate view. The figures are annual citywide totals, not district-level cuts.",
  sources: [
    {
      label: "Comune di Milano open data: reported crimes 2004-2023",
      url: "https://dati.comune.milano.it/dataset/34e2d2af-5c3b-4768-918b-ab7e5c0d15da",
    },
    {
      label: "Comune di Milano open data: calculated resident population by sex 1936-2023",
      url: "https://dati.comune.milano.it/dataset/2ba2e01c-51db-48c6-a330-776bb4c5a023",
    },
  ],
  categories: [
    {
      sourceLabels: ["Reati totale"],
      label: "All recorded offenses",
      shortLabel: "All offenses",
      color: "#7dd3fc",
      isDefault: false,
      sortOrder: 1,
    },
    {
      sourceLabels: ["Furti"],
      label: "Theft",
      shortLabel: "Theft",
      color: "#facc15",
      isDefault: true,
      sortOrder: 2,
    },
    {
      sourceLabels: ["Rapine totale"],
      label: "Robbery",
      shortLabel: "Robbery",
      color: "#f97316",
      isDefault: true,
      sortOrder: 3,
    },
    {
      sourceLabels: ["Violenze sessuali"],
      label: "Sexual violence",
      shortLabel: "Sexual violence",
      color: "#ec4899",
      isDefault: true,
      sortOrder: 4,
    },
    {
      sourceLabels: ["Lesioni dolose"],
      label: "Assaults",
      shortLabel: "Assaults",
      color: "#fde047",
      isDefault: false,
      sortOrder: 5,
    },
    {
      sourceLabels: ["Furti  in abitazioni"],
      label: "Residential burglary",
      shortLabel: "Res. burglary",
      color: "#ef4444",
      isDefault: false,
      sortOrder: 6,
    },
    {
      sourceLabels: ["Furti di autovetture"],
      label: "Vehicle theft",
      shortLabel: "Vehicle theft",
      color: "#4f46e5",
      isDefault: true,
      sortOrder: 7,
    },
    {
      sourceLabels: ["Truffe e frodi informatiche"],
      label: "Cyber fraud",
      shortLabel: "Cyber fraud",
      color: "#38bdf8",
      isDefault: true,
      sortOrder: 8,
    },
    {
      sourceLabels: ["Danneggiamenti"],
      label: "Criminal damage",
      shortLabel: "Criminal damage",
      color: "#fb7185",
      isDefault: true,
      sortOrder: 9,
    },
    {
      sourceLabels: ["Normativa sugli stupefacenti"],
      label: "Drug offenses",
      shortLabel: "Drug offenses",
      color: "#22c55e",
      isDefault: true,
      sortOrder: 10,
    },
    {
      sourceLabels: ["Omicidi volontari totale"],
      label: "Homicide",
      shortLabel: "Homicide",
      color: "#be123c",
      isDefault: false,
      sortOrder: 11,
    },
    {
      sourceLabels: ["Tentati omicidi"],
      label: "Attempted homicide",
      shortLabel: "Attempted homicide",
      color: "#fda4af",
      isDefault: false,
      sortOrder: 12,
    },
    {
      sourceLabels: ["Incendi totale"],
      label: "Arson and fires",
      shortLabel: "Arson",
      color: "#f59e0b",
      isDefault: false,
      sortOrder: 13,
    },
  ],
};

export const NEW_YORK_CITY_LOCATION: LocationDefinition = {
  slug: "new-york-city",
  label: "New York City",
  country: "United States",
  areaLabelSingular: "Borough",
  areaLabelPlural: "Boroughs",
  chartTitle: "New York City Crime by Borough",
  note:
    "New York City uses the official NYPD complaint open-data feeds. The dashboard aggregates official borough-level complaint records to calendar years and shows a mapped set of major offense groups from the NYPD catalog.",
  sources: [
    {
      label: "NYC Open Data: NYPD Complaint Data Historic",
      url: "https://data.cityofnewyork.us/Public-Safety/NYPD-Complaint-Data-Historic/qgea-i56i",
    },
    {
      label: "NYC Open Data: NYPD Complaint Data Current",
      url: "https://data.cityofnewyork.us/Public-Safety/NYPD-Complaint-Data-Current-2025-/5uac-w243",
    },
  ],
  categories: [
    {
      sourceLabels: ["MURDER & NON-NEGL. MANSLAUGHTER"],
      label: "Homicide",
      shortLabel: "Homicide",
      color: "#be123c",
      isDefault: false,
      sortOrder: 1,
    },
    {
      sourceLabels: ["RAPE"],
      label: "Rape",
      shortLabel: "Rape",
      color: "#f472b6",
      isDefault: true,
      sortOrder: 2,
    },
    {
      sourceLabels: ["SEX CRIMES"],
      label: "Other sexual offenses",
      shortLabel: "Other sexual",
      color: "#ec4899",
      isDefault: false,
      sortOrder: 3,
    },
    {
      sourceLabels: ["ROBBERY"],
      label: "Robbery",
      shortLabel: "Robbery",
      color: "#f97316",
      isDefault: true,
      sortOrder: 4,
    },
    {
      sourceLabels: ["BURGLARY"],
      label: "Burglary",
      shortLabel: "Burglary",
      color: "#ef4444",
      isDefault: true,
      sortOrder: 5,
    },
    {
      sourceLabels: ["FELONY ASSAULT"],
      label: "Felony assault",
      shortLabel: "Felony assault",
      color: "#facc15",
      isDefault: true,
      sortOrder: 6,
    },
    {
      sourceLabels: ["PETIT LARCENY"],
      label: "Petit larceny",
      shortLabel: "Petit larceny",
      color: "#fde047",
      isDefault: false,
      sortOrder: 7,
    },
    {
      sourceLabels: ["GRAND LARCENY"],
      label: "Grand larceny",
      shortLabel: "Grand larceny",
      color: "#38bdf8",
      isDefault: true,
      sortOrder: 8,
    },
    {
      sourceLabels: ["GRAND LARCENY OF MOTOR VEHICLE"],
      label: "Motor vehicle theft",
      shortLabel: "Vehicle theft",
      color: "#4f46e5",
      isDefault: true,
      sortOrder: 9,
    },
    {
      sourceLabels: ["DANGEROUS DRUGS"],
      label: "Drug offenses",
      shortLabel: "Drug offenses",
      color: "#22c55e",
      isDefault: true,
      sortOrder: 10,
    },
    {
      sourceLabels: ["DANGEROUS WEAPONS"],
      label: "Weapons offenses",
      shortLabel: "Weapons",
      color: "#14b8a6",
      isDefault: false,
      sortOrder: 11,
    },
    {
      sourceLabels: ["CRIMINAL MISCHIEF & RELATED OF"],
      label: "Criminal mischief",
      shortLabel: "Criminal mischief",
      color: "#fb7185",
      isDefault: false,
      sortOrder: 12,
    },
    {
      sourceLabels: ["THEFT-FRAUD", "FRAUDS", "OFFENSES INVOLVING FRAUD", "FORGERY"],
      label: "Fraud and forgery",
      shortLabel: "Fraud & forgery",
      color: "#94a3b8",
      isDefault: false,
      sortOrder: 13,
    },
  ],
};

export const CHICAGO_LOCATION: LocationDefinition = {
  slug: "chicago",
  label: "Chicago",
  country: "United States",
  areaLabelSingular: "District",
  areaLabelPlural: "Districts",
  chartTitle: "Chicago Crime by District",
  note:
    "Chicago uses the official city open-data crime feed. The dashboard aggregates official district-level incident records to calendar years and maps the major offense groups published in the city dataset.",
  sources: [
    {
      label: "Chicago Data Portal: Crimes 2001 to Present",
      url: "https://data.cityofchicago.org/Public-Safety/Crimes-2001-to-Present/ijzp-q8t2",
    },
  ],
  categories: [
    {
      sourceLabels: ["HOMICIDE"],
      label: "Homicide",
      shortLabel: "Homicide",
      color: "#be123c",
      isDefault: false,
      sortOrder: 1,
    },
    {
      sourceLabels: ["CRIMINAL SEXUAL ASSAULT", "CRIM SEXUAL ASSAULT"],
      label: "Criminal sexual assault",
      shortLabel: "Sexual assault",
      color: "#f472b6",
      isDefault: true,
      sortOrder: 2,
    },
    {
      sourceLabels: ["SEX OFFENSE"],
      label: "Other sexual offenses",
      shortLabel: "Other sexual",
      color: "#ec4899",
      isDefault: false,
      sortOrder: 3,
    },
    {
      sourceLabels: ["ROBBERY"],
      label: "Robbery",
      shortLabel: "Robbery",
      color: "#f97316",
      isDefault: true,
      sortOrder: 4,
    },
    {
      sourceLabels: ["BURGLARY"],
      label: "Burglary",
      shortLabel: "Burglary",
      color: "#ef4444",
      isDefault: true,
      sortOrder: 5,
    },
    {
      sourceLabels: ["ASSAULT"],
      label: "Assault",
      shortLabel: "Assault",
      color: "#facc15",
      isDefault: false,
      sortOrder: 6,
    },
    {
      sourceLabels: ["BATTERY"],
      label: "Battery",
      shortLabel: "Battery",
      color: "#fde047",
      isDefault: true,
      sortOrder: 7,
    },
    {
      sourceLabels: ["THEFT"],
      label: "Theft",
      shortLabel: "Theft",
      color: "#38bdf8",
      isDefault: true,
      sortOrder: 8,
    },
    {
      sourceLabels: ["MOTOR VEHICLE THEFT"],
      label: "Motor vehicle theft",
      shortLabel: "Vehicle theft",
      color: "#4f46e5",
      isDefault: true,
      sortOrder: 9,
    },
    {
      sourceLabels: ["NARCOTICS"],
      label: "Drug offenses",
      shortLabel: "Drug offenses",
      color: "#22c55e",
      isDefault: true,
      sortOrder: 10,
    },
    {
      sourceLabels: ["WEAPONS VIOLATION"],
      label: "Weapons offenses",
      shortLabel: "Weapons",
      color: "#14b8a6",
      isDefault: false,
      sortOrder: 11,
    },
    {
      sourceLabels: ["CRIMINAL DAMAGE"],
      label: "Criminal damage",
      shortLabel: "Criminal damage",
      color: "#fb7185",
      isDefault: true,
      sortOrder: 12,
    },
    {
      sourceLabels: ["DECEPTIVE PRACTICE"],
      label: "Fraud and deception",
      shortLabel: "Fraud",
      color: "#94a3b8",
      isDefault: false,
      sortOrder: 13,
    },
    {
      sourceLabels: ["ARSON"],
      label: "Arson",
      shortLabel: "Arson",
      color: "#f59e0b",
      isDefault: false,
      sortOrder: 14,
    },
  ],
};

export const LOS_ANGELES_LOCATION: LocationDefinition = {
  slug: "los-angeles",
  label: "Los Angeles",
  country: "United States",
  areaLabelSingular: "Area",
  areaLabelPlural: "Areas",
  chartTitle: "Los Angeles Crime by Area",
  note:
    "Los Angeles uses the official LAPD crime open-data feeds. The dashboard aggregates area-level incident records to calendar years and groups the official raw offense descriptions into stable major offense buckets.",
  sources: [
    {
      label: "Los Angeles Open Data: Crime Data from 2010 to 2019",
      url: "https://data.lacity.org/Public-Safety/Crime-Data-from-2010-to-2019/63jg-8b9z",
    },
    {
      label: "Los Angeles Open Data: Crime Data from 2020 to Present",
      url: "https://data.lacity.org/Public-Safety/Crime-Data-from-2020-to-Present/2nrs-mtv8",
    },
  ],
  categories: [
    {
      sourceLabels: ["CRIMINAL HOMICIDE"],
      label: "Homicide",
      shortLabel: "Homicide",
      color: "#be123c",
      isDefault: false,
      sortOrder: 1,
    },
    {
      sourceLabels: [
        "RAPE, FORCIBLE",
        "RAPE, ATTEMPTED",
        "SEX,UNLAWFUL(INC MUTUAL CONSENT, PENETRATION W/ FRGN OBJ",
        "SEXUAL PENETRATION W/FOREIGN OBJECT",
        "ORAL COPULATION",
        "SODOMY/SEXUAL CONTACT B/W PENIS OF ONE PERS TO ANUS OTH",
        "BATTERY WITH SEXUAL CONTACT",
        "INDECENT EXPOSURE",
        "LEWD CONDUCT",
        "PEEPING TOM",
      ],
      label: "Sexual offenses",
      shortLabel: "Sexual offenses",
      color: "#ec4899",
      isDefault: true,
      sortOrder: 2,
    },
    {
      sourceLabels: ["ROBBERY", "ATTEMPTED ROBBERY"],
      label: "Robbery",
      shortLabel: "Robbery",
      color: "#f97316",
      isDefault: true,
      sortOrder: 3,
    },
    {
      sourceLabels: ["BURGLARY", "BURGLARY, ATTEMPTED"],
      label: "Burglary",
      shortLabel: "Burglary",
      color: "#ef4444",
      isDefault: true,
      sortOrder: 4,
    },
    {
      sourceLabels: [
        "THEFT PLAIN - PETTY ($950 & UNDER)",
        "THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LIVESTK,PROD",
        "SHOPLIFTING - PETTY THEFT ($950 & UNDER)",
        "SHOPLIFTING-GRAND THEFT ($950.01 & OVER)",
        "THEFT, PERSON",
        "BIKE - STOLEN",
        "THEFT PLAIN - ATTEMPT",
      ],
      label: "Theft",
      shortLabel: "Theft",
      color: "#facc15",
      isDefault: true,
      sortOrder: 5,
    },
    {
      sourceLabels: [
        "BURGLARY FROM VEHICLE",
        "BURGLARY FROM VEHICLE, ATTEMPTED",
        "THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER)",
        "THEFT FROM MOTOR VEHICLE - GRAND ($950.01 AND OVER)",
        "THEFT FROM MOTOR VEHICLE - ATTEMPT",
      ],
      label: "Theft from vehicles",
      shortLabel: "From vehicles",
      color: "#14b8a6",
      isDefault: false,
      sortOrder: 6,
    },
    {
      sourceLabels: ["VEHICLE - STOLEN", "VEHICLE - ATTEMPT STOLEN"],
      label: "Motor vehicle theft",
      shortLabel: "Vehicle theft",
      color: "#4f46e5",
      isDefault: true,
      sortOrder: 7,
    },
    {
      sourceLabels: [
        "BATTERY - SIMPLE ASSAULT",
        "INTIMATE PARTNER - SIMPLE ASSAULT",
        "ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",
        "INTIMATE PARTNER - AGGRAVATED ASSAULT",
        "OTHER ASSAULT",
        "CHILD ABUSE (PHYSICAL) - SIMPLE ASSAULT",
        "CHILD ABUSE (PHYSICAL) - AGGRAVATED ASSAULT",
      ],
      label: "Assaults",
      shortLabel: "Assaults",
      color: "#38bdf8",
      isDefault: true,
      sortOrder: 8,
    },
    {
      sourceLabels: [
        "VANDALISM - FELONY ($400 & OVER, ALL CHURCH VANDALISMS)",
        "VANDALISM - MISDEAMEANOR ($399 OR UNDER)",
        "ARSON",
      ],
      label: "Criminal damage",
      shortLabel: "Criminal damage",
      color: "#fb7185",
      isDefault: true,
      sortOrder: 9,
    },
    {
      sourceLabels: [
        "THEFT OF IDENTITY",
        "DOCUMENT FORGERY / STOLEN FELONY",
        "BUNCO, GRAND THEFT",
        "EMBEZZLEMENT, GRAND THEFT ($950.01 & OVER)",
        "BUNCO, PETTY THEFT",
        "UNAUTHORIZED COMPUTER ACCESS",
        "COUNTERFEIT",
        "CREDIT CARDS, FRAUD USE ($950.01 & OVER)",
        "BUNCO, ATTEMPT",
      ],
      label: "Fraud and forgery",
      shortLabel: "Fraud & forgery",
      color: "#94a3b8",
      isDefault: false,
      sortOrder: 10,
    },
    {
      sourceLabels: [
        "BRANDISH WEAPON",
        "DISCHARGE FIREARMS/SHOTS FIRED",
        "SHOTS FIRED AT INHABITED DWELLING",
      ],
      label: "Weapons incidents",
      shortLabel: "Weapons",
      color: "#67e8f9",
      isDefault: false,
      sortOrder: 11,
    },
  ],
};

export const SAN_FRANCISCO_LOCATION: LocationDefinition = {
  slug: "san-francisco",
  label: "San Francisco",
  country: "United States",
  areaLabelSingular: "Police District",
  areaLabelPlural: "Police Districts",
  chartTitle: "San Francisco Crime by Police District",
  note:
    "San Francisco uses the official Police Department incident-reports open-data feed. The dashboard aggregates police-district records to calendar years and shows the major incident categories published in the city dataset.",
  sources: [
    {
      label: "San Francisco Open Data: Police Department Incident Reports 2018 to Present",
      url: "https://data.sfgov.org/Public-Safety/Police-Department-Incident-Reports-2018-to-Present/wg3w-h783",
    },
  ],
  categories: [
    {
      sourceLabels: ["Homicide"],
      label: "Homicide",
      shortLabel: "Homicide",
      color: "#be123c",
      isDefault: false,
      sortOrder: 1,
    },
    {
      sourceLabels: ["Rape"],
      label: "Rape",
      shortLabel: "Rape",
      color: "#f472b6",
      isDefault: true,
      sortOrder: 2,
    },
    {
      sourceLabels: ["Sex Offense"],
      label: "Other sexual offenses",
      shortLabel: "Other sexual",
      color: "#ec4899",
      isDefault: false,
      sortOrder: 3,
    },
    {
      sourceLabels: ["Robbery"],
      label: "Robbery",
      shortLabel: "Robbery",
      color: "#f97316",
      isDefault: true,
      sortOrder: 4,
    },
    {
      sourceLabels: ["Burglary"],
      label: "Burglary",
      shortLabel: "Burglary",
      color: "#ef4444",
      isDefault: true,
      sortOrder: 5,
    },
    {
      sourceLabels: ["Assault"],
      label: "Assault",
      shortLabel: "Assault",
      color: "#facc15",
      isDefault: true,
      sortOrder: 6,
    },
    {
      sourceLabels: ["Larceny Theft"],
      label: "Larceny theft",
      shortLabel: "Larceny theft",
      color: "#38bdf8",
      isDefault: true,
      sortOrder: 7,
    },
    {
      sourceLabels: ["Motor Vehicle Theft", "Motor Vehicle Theft?"],
      label: "Motor vehicle theft",
      shortLabel: "Vehicle theft",
      color: "#4f46e5",
      isDefault: true,
      sortOrder: 8,
    },
    {
      sourceLabels: ["Drug Offense", "Drug Violation"],
      label: "Drug offenses",
      shortLabel: "Drug offenses",
      color: "#22c55e",
      isDefault: true,
      sortOrder: 9,
    },
    {
      sourceLabels: ["Weapons Offense", "Weapons Carrying Etc", "Weapons Offence"],
      label: "Weapons offenses",
      shortLabel: "Weapons",
      color: "#14b8a6",
      isDefault: false,
      sortOrder: 10,
    },
    {
      sourceLabels: ["Fraud", "Forgery And Counterfeiting", "Embezzlement"],
      label: "Fraud and forgery",
      shortLabel: "Fraud & forgery",
      color: "#94a3b8",
      isDefault: false,
      sortOrder: 11,
    },
    {
      sourceLabels: ["Malicious Mischief", "Vandalism", "Arson"],
      label: "Criminal damage",
      shortLabel: "Criminal damage",
      color: "#fb7185",
      isDefault: true,
      sortOrder: 12,
    },
  ],
};

export const LOCATION_DEFINITIONS: LocationDefinition[] = [
  BERLIN_LOCATION,
  BARCELONA_LOCATION,
  CHICAGO_LOCATION,
  FRANKFURT_LOCATION,
  LONDON_LOCATION,
  LOS_ANGELES_LOCATION,
  LUTON_LOCATION,
  MILAN_LOCATION,
  NEW_YORK_CITY_LOCATION,
  PARIS_LOCATION,
  ROME_LOCATION,
  SAO_PAULO_LOCATION,
  SAN_FRANCISCO_LOCATION,
  TOKYO_LOCATION,
  VALENCIA_LOCATION,
];
